#include <iostream.h>
#include <dos.h>
#include <conio.h>
#include <stdlib.h>
#include <iomanip.h>
#include <time.h>
   int main()
   {
    char name[30];
    int ch1;

  textcolor (11);
  clrscr();
  sleep (1);
  cout << "\n\n";
  cout << "  ²²²²   ²²²²²²Ü ²²²²²²Ü ²²²²²²Ü  ²²²²   ²²Ü  ²²Ü  ²Ü ²²²²²²Ü  ²²²²²Ü ²²²²Ü   \n";
  delay (80);
  cout << " ²²Ûß²²Ü ²²Ûßß²Û ²²Ûßß²Û ²²Ûßß²Û ²²Ûß²²Ü ²²Û  ²²Û  ²Û ²²Ûßß²Û ²²Ûßßßß ²²Ûßß   \n";
  delay (80);
  cout << " ²²Û ²²Û ²²Û  ²Û ²²Û  ²Û ²²Û   ß ²²Û ²²Û ²²Û  ²²Û  ²Û ²²Û  ²Û ²²Û     ²²Û     \n";
  delay (60);
  cout << " ²²²²²²Û ²²²²²²Û ²²Û  ²Û ²²Û     ²²²²²²Û ²²Û  ²²²²²²Û ²²²²²²Û  ²²²²   ²²²²²Ü  \n";
  delay (50);
  cout << " ²²Ûßß²Û ²²Ûßßßß ²²Û  ²Û ²²Û     ²²Ûßß²Û ²²Û   ßß²²Ûß ²²Ûßßßß   ßß²²Ü ²²Ûßßß  \n";
  delay (50);
  cout << " ²²Û  ²Û ²²Û     ²²Û  ²Û ²²Û     ²²Û  ²Û ²²Û     ²²Û  ²²Û         ²²Û ²²Û     \n";
  delay (50);
  cout << " ²²Û  ²Û ²²Û     ²²Û  ²Û ²²Û  ²Ü ²²Û  ²Û ²²Û     ²²Û  ²²Û        ²²²Û ²²Û     \n";
  delay (50);
  cout << " ²²Û  ²Û ²²Û     ²²²²²²Û ²²²²²²Û ²²Û  ²Û ²²²²²Ü  ²²Û  ²²Û     ²²²²²Ûß ²²²²²²²Ü\n";
  delay (40);
  cout << "  ßß   ß  ßß      ßßßßßß  ßßßßßß  ßß   ß  ßßßßß   ßß   ßß      ßßßßß   ßßßßß²Û\n";
  cout << "                                                                           ²²Û\n";
  delay (80);
  cout << "²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²Ûß\n";
  cout << " ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß";
  sleep (1);
  cout << "\n";
  cout << "                             Presents...";
  sleep (4);
  textcolor(2);
  clrscr();
  cout << "\n\n\n";
  cout << "        °°°°±   ±±²²²  ²²±±  ±  °    \n";
  cout << "        °°  ±±    ²    ²  ±  ± ±     \n";
  cout << "        °°  ±±    ²    ²²±±  ±±      \n";
  cout << "        °°  ±±    ²    ² ±   ± ±     \n";
  cout << "        °°°°±   ±±²²²  ²  ±  ±  °    \n";
  cout << "                 AND THE\n";
  cout << "             TIME RIPPERS\n\n\n\n\n";
  cout << "         Press any key to continue";
  getch();
  ch1 = 0;
  while (ch1 < 4)
 {
  ch1 = 0;
  textcolor (15);
  clrscr();
  cout << "----MAIN---MENU-----------------------------------------\n\n";
  cout << "    °±²Û  1  ::  INTRODUCTION\n\n";
  cout << "    °±²Û  2  ::  PLAY THE GAME\n\n";
  cout << "    °±²Û  3  ::  CREDITS (Waste of time)\n\n";
  cout << "    °±²Û  4  ::  EXIT\n\n";
  cout << "CHOICE: ";
  cin >> (ch1);
  if ((ch1 == 1) != 0)
   {
    textcolor (12);
    clrscr();
    cout << "\n\n\n\n\n\n\n";
    cout << "     O
    getch();
    textcolor (11);
    clrscr();

  }
 }
  }