SCREEN 12 'BEGINING
10 CLS
LINE (100, 180)-(480, 260), 1, B
LINE (101, 181)-(479, 259), 1, B
LINE (102, 182)-(478, 258), 1, B
LINE (103, 183)-(477, 257), 9, B
LINE (104, 184)-(476, 256), 9, B
LINE (105, 185)-(475, 255), 9, B
LINE (106, 186)-(474, 254), 11, B
LINE (107, 187)-(473, 253), 11, B
LINE (108, 188)-(472, 252), 11, B
LINE (109, 189)-(471, 251), 15, B
LINE (110, 190)-(470, 250), 15, B
LINE (111, 191)-(469, 249), 15, B
LINE (112, 192)-(468, 248), 7, B
LINE (113, 193)-(467, 247), 7, B
LINE (114, 194)-(466, 246), 7, B
LINE (115, 195)-(465, 245), 8, B
LINE (116, 196)-(464, 244), 8, B
LINE (117, 197)-(463, 243), 8, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "L16 D"
CLS
LINE (100, 180)-(480, 260), 8, B
LINE (101, 181)-(479, 259), 1, B
LINE (102, 182)-(478, 258), 1, B
LINE (103, 183)-(477, 257), 1, B
LINE (104, 184)-(476, 256), 9, B
LINE (105, 185)-(475, 255), 9, B
LINE (106, 186)-(474, 254), 9, B
LINE (107, 187)-(473, 253), 11, B
LINE (108, 188)-(472, 252), 11, B
LINE (109, 189)-(471, 251), 11, B
LINE (110, 190)-(470, 250), 15, B
LINE (111, 191)-(469, 249), 15, B
LINE (112, 192)-(468, 248), 15, B
LINE (113, 193)-(467, 247), 7, B
LINE (114, 194)-(466, 246), 7, B
LINE (115, 195)-(465, 245), 7, B
LINE (116, 196)-(464, 244), 8, B
LINE (117, 197)-(463, 243), 8, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "E"
CLS
LINE (100, 180)-(480, 260), 8, B
LINE (101, 181)-(479, 259), 8, B
LINE (102, 182)-(478, 258), 1, B
LINE (103, 183)-(477, 257), 1, B
LINE (104, 184)-(476, 256), 1, B
LINE (105, 185)-(475, 255), 9, B
LINE (106, 186)-(474, 254), 9, B
LINE (107, 187)-(473, 253), 9, B
LINE (108, 188)-(472, 252), 11, B
LINE (109, 189)-(471, 251), 11, B
LINE (110, 190)-(470, 250), 11, B
LINE (111, 191)-(469, 249), 15, B
LINE (112, 192)-(468, 248), 15, B
LINE (113, 193)-(467, 247), 15, B
LINE (114, 194)-(466, 246), 7, B
LINE (115, 195)-(465, 245), 7, B
LINE (116, 196)-(464, 244), 7, B
LINE (117, 197)-(463, 243), 8, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "F"
CLS
LINE (100, 180)-(480, 260), 8, B
LINE (101, 181)-(479, 259), 8, B
LINE (102, 182)-(478, 258), 8, B
LINE (103, 183)-(477, 257), 1, B
LINE (104, 184)-(476, 256), 1, B
LINE (105, 185)-(475, 255), 1, B
LINE (106, 186)-(474, 254), 9, B
LINE (107, 187)-(473, 253), 9, B
LINE (108, 188)-(472, 252), 9, B
LINE (109, 189)-(471, 251), 11, B
LINE (110, 190)-(470, 250), 11, B
LINE (111, 191)-(469, 249), 11, B
LINE (112, 192)-(468, 248), 15, B
LINE (113, 193)-(467, 247), 15, B
LINE (114, 194)-(466, 246), 15, B
LINE (115, 195)-(465, 245), 7, B
LINE (116, 196)-(464, 244), 7, B
LINE (117, 197)-(463, 243), 7, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "G#"
CLS
LINE (100, 180)-(480, 260), 7, B
LINE (101, 181)-(479, 259), 8, B
LINE (102, 182)-(478, 258), 8, B
LINE (103, 183)-(477, 257), 8, B
LINE (104, 184)-(476, 256), 1, B
LINE (105, 185)-(475, 255), 1, B
LINE (106, 186)-(474, 254), 1, B
LINE (107, 187)-(473, 253), 9, B
LINE (108, 188)-(472, 252), 9, B
LINE (109, 189)-(471, 251), 9, B
LINE (110, 190)-(470, 250), 11, B
LINE (111, 191)-(469, 249), 11, B
LINE (112, 192)-(468, 248), 11, B
LINE (113, 193)-(467, 247), 15, B
LINE (114, 194)-(466, 246), 15, B
LINE (115, 195)-(465, 245), 15, B
LINE (116, 196)-(464, 244), 7, B
LINE (117, 197)-(463, 243), 7, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "A"
CLS
LINE (100, 180)-(480, 260), 7, B
LINE (101, 181)-(479, 259), 7, B
LINE (102, 182)-(478, 258), 8, B
LINE (103, 183)-(477, 257), 8, B
LINE (104, 184)-(476, 256), 8, B
LINE (105, 185)-(475, 255), 1, B
LINE (106, 186)-(474, 254), 1, B
LINE (107, 187)-(473, 253), 1, B
LINE (108, 188)-(472, 252), 9, B
LINE (109, 189)-(471, 251), 9, B
LINE (110, 190)-(470, 250), 9, B
LINE (111, 191)-(469, 249), 11, B
LINE (112, 192)-(468, 248), 11, B
LINE (113, 193)-(467, 247), 11, B
LINE (114, 194)-(466, 246), 15, B
LINE (115, 195)-(465, 245), 15, B
LINE (116, 196)-(464, 244), 15, B
LINE (117, 197)-(463, 243), 7, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "G#"
CLS
LINE (100, 180)-(480, 260), 7, B
LINE (101, 181)-(479, 259), 7, B
LINE (102, 182)-(478, 258), 7, B
LINE (103, 183)-(477, 257), 8, B
LINE (104, 184)-(476, 256), 8, B
LINE (105, 185)-(475, 255), 8, B
LINE (106, 186)-(474, 254), 1, B
LINE (107, 187)-(473, 253), 1, B
LINE (108, 188)-(472, 252), 1, B
LINE (109, 189)-(471, 251), 9, B
LINE (110, 190)-(470, 250), 9, B
LINE (111, 191)-(469, 249), 9, B
LINE (112, 192)-(468, 248), 11, B
LINE (113, 193)-(467, 247), 11, B
LINE (114, 194)-(466, 246), 11, B
LINE (115, 195)-(465, 245), 15, B
LINE (116, 196)-(464, 244), 15, B
LINE (117, 197)-(463, 243), 15, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "F"
CLS
LINE (100, 180)-(480, 260), 15, B
LINE (101, 181)-(479, 259), 7, B
LINE (102, 182)-(478, 258), 7, B
LINE (103, 183)-(477, 257), 7, B
LINE (104, 184)-(476, 256), 8, B
LINE (105, 185)-(475, 255), 8, B
LINE (106, 186)-(474, 254), 8, B
LINE (107, 187)-(473, 253), 1, B
LINE (108, 188)-(472, 252), 1, B
LINE (109, 189)-(471, 251), 1, B
LINE (110, 190)-(470, 250), 9, B
LINE (111, 191)-(469, 249), 9, B
LINE (112, 192)-(468, 248), 9, B
LINE (113, 193)-(467, 247), 11, B
LINE (114, 194)-(466, 246), 11, B
LINE (115, 195)-(465, 245), 11, B
LINE (116, 196)-(464, 244), 15, B
LINE (117, 197)-(463, 243), 15, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "E"
CLS
LINE (100, 180)-(480, 260), 15, B
LINE (101, 181)-(479, 259), 15, B
LINE (102, 182)-(478, 258), 7, B
LINE (103, 183)-(477, 257), 7, B
LINE (104, 184)-(476, 256), 7, B
LINE (105, 185)-(475, 255), 8, B
LINE (106, 186)-(474, 254), 8, B
LINE (107, 187)-(473, 253), 8, B
LINE (108, 188)-(472, 252), 1, B
LINE (109, 189)-(471, 251), 1, B
LINE (110, 190)-(470, 250), 1, B
LINE (111, 191)-(469, 249), 9, B
LINE (112, 192)-(468, 248), 9, B
LINE (113, 193)-(467, 247), 9, B
LINE (114, 194)-(466, 246), 11, B
LINE (115, 195)-(465, 245), 11, B
LINE (116, 196)-(464, 244), 11, B
LINE (117, 197)-(463, 243), 15, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "D"
PLAY "E F G# A G# F E D E F G# A G# F E L6 A."
CLS
CIRCLE (319, 239), 2, 8
PAINT (320, 240), 8, 8
PLAY "L18 < B. >"
CLS
CIRCLE (319, 239), 4, 7
PAINT (320, 240), 7, 7
PLAY " C "
CLS
CIRCLE (319, 239), 8, 15
PAINT (320, 240), 15, 15
PLAY "D."
CLS
CIRCLE (319, 239), 14, 12
PAINT (320, 240), 12, 12
PLAY "C#"
CLS
CIRCLE (319, 239), 20, 4
PAINT (320, 240), 4, 4
PLAY "< B >"
CLS
CIRCLE (319, 239), 26, 6
PAINT (320, 240), 6, 6
PLAY "C#"
CLS
CIRCLE (319, 239), 32, 8
PAINT (320, 240), 8, 8
PLAY "E"
CLS
CIRCLE (319, 239), 40, 7
PAINT (320, 240), 7, 7
LOCATE 14, 35
PRINT "DI"
PLAY "< A"
CLS
CIRCLE (319, 239), 50, 15
PAINT (320, 240), 15, 15
LOCATE 14, 35
PRINT "DIRK"
PLAY "L4 F"
CLS
CIRCLE (319, 239), 62, 11
PAINT (320, 240), 11, 11
LOCATE 14, 35
PRINT "DIRK G"
PLAY "L16 E."
CLS
CIRCLE (319, 239), 75, 9
PAINT (320, 240), 9, 9
LOCATE 14, 35
PRINT "DIRK GIR"
PLAY "C#"
CLS
CIRCLE (319, 239), 100, 1
PAINT (320, 240), 1, 1
LOCATE 14, 35
PRINT "DIRK  GIRKL"
PLAY "L6 A > "
CLS
CIRCLE (319, 239), 120, 13
PAINT (320, 240), 13, 13
LOCATE 14, 35
PRINT "DIRK GIRKLIN"
BEEP
CLS
CIRCLE (319, 239), 120, 13
PAINT (320, 240), 13, 13
LOCATE 14, 35
PRINT "DIRK GIRKLIN"
LOCATE 16, 28
PRINT "THE LIQUID ARMPIT PUTTY"
LOCATE 30, 1
INPUT "Press ENTER"; en$
IF en$ = "6132" THEN GOTO 341:  ELSE GOTO 11
11 CLS
LOCATE 3, 32
PRINT "***********"
LOCATE 4, 33
PRINT "MAIN MENU"      'MENU
LOCATE 5, 32
PRINT "***********"
LOCATE 12, 1
PRINT "                      (1) TITLE"
PRINT
PRINT "                      (2) INTRODUCTION"
PRINT
PRINT "                      (3) GAME"
PRINT
PRINT "                      (4) CREDITS"
PRINT
PRINT "                      CTRL BREAK TO EXIT "
PRINT
INPUT "Which number do wish to choose"; num!
IF num! = 1 THEN GOTO 10:  ELSE GOTO 13
13 IF num! = 2 THEN GOTO 40:  ELSE GOTO 14
14 IF num! = 3 THEN GOTO 60:  ELSE GOTO 15
15 IF num! = 4 THEN GOTO 20:  ELSE GOTO 16
16 PRINT "Invalid selection"
GOTO 11                       'CREDITS
20 CLS
LOCATE 4, 28
PRINT "  CREDITS"
PRINT "            GRAPHICS BY-------GARY BURT"
PRINT "              PROGRAMMER--------GARY BURT"
PRINT "                STORY BY----------GARY BURT"
PRINT "  EVERYTHING ELSE BY------------GARY BURT"
PRINT
PRINT "         ****SPECIAL THANKS TO****"
PRINT "      HAPPY  TOWNE  PROGRAMMING  INC."
LOCATE 30, 25
INPUT "Press ENTER"; en$
GOTO 11
40 CLS
PRINT "Long ago... On the planet Fortunius, a strange experiment is begining."
CIRCLE (320, 240), 110, 15
CIRCLE (319, 239), 109, 7
CIRCLE (318, 238), 108, 9
CIRCLE (317, 237), 107, 1
CIRCLE (315, 235), 105, 1             'INTRODUCTION
LOCATE 30, 5
INPUT "Press ENTER"; en$
CLS
PLAY "< < < B < C+"
BEEP
PRINT
PRINT "A suden explosion echoed through the planet. Then over time the"
PRINT "planet began to melt. Then a huge ugly ooze formed. It grabbed"
PRINT "all organic life on Fortunius and it came to life. Now 1000 years"
PRINT "later an odd liquid has been eating planets. And nothing has been"
PRINT "been able to stop it..."
LOCATE 13, 1
LINE (1, 240)-(640, 240), 2
PRINT "We leave Dirk shopping for a nifty warp engine at Stud's Engines."
LOCATE 28, 1
INPUT "Press ENTER"; en$          'GAME
GOTO 11
60 CLS
PRINT "  |  How much for this Ace Warp Engine?|, you ask."
PRINT
PRINT "  |  Only 9100.98 Creds.|, says the shopkeeper."
PRINT
PRINT " Dirk looks in horror at the price tag! It was alot. He turned"
PRINT "and strolled off out to his green spacemobile."
CIRCLE (270, 250), 55, 15 'cockpit
LINE (179, 259)-(360, 320), 2, B 'ship body
PAINT (180, 260), 2, 2
CIRCLE (279, 239), 16, 14 'head
PAINT (280, 240), 14, 14
LINE (155, 250)-(55, 250), 15
LINE (150, 300)-(45, 300), 15
LOCATE 18, 5
PRINT "***ZOOOM!***"
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
68 PRINT "Now which three planets do you wish to go?" 'GRAPH SELECTION #1
LINE (100, 80)-(600, 450), 12, B
LINE (101, 81)-(599, 449), 12, B
CIRCLE (320, 240), 6, 15
CIRCLE (320, 240), 5, 11
CIRCLE (320, 240), 4, 9
CIRCLE (320, 240), 3, 1
LOCATE 17, 34
PRINT "-B- You are here.(Xen Shopping Center)"
CIRCLE (179, 129), 6, 4
PAINT (180, 130), 4, 4
LOCATE 7, 16
PRINT "-A- Numinos"
CIRCLE (429, 359), 6, 13
PAINT (430, 360), 13, 13
LOCATE 22, 50
PRINT "-C- (Unknown)"
LOCATE 30, 1
70 INPUT "Which letter do you wish to choose (a/b/c)"; acb$
IF acb$ = "a" THEN GOTO 210:   ELSE GOTO 72
72 IF acb$ = "b" THEN GOTO 100:  ELSE GOTO 74
74 IF acb$ = "c" THEN GOTO 300:  ELSE GOTO 76
76 PRINT "That is not an option. All answers must be in lower case."
GOTO 70
 
100 CLS
PRINT "You zoom into the giant parking lot of the Xen Shopping Center."
PRINT "You can see only 2 stores open now."
PRINT "(a) = Al's Foods"
PRINT "(b) = Joe's survival gear"
PRINT
102 INPUT "Which store do you wish to go in (a/b)"; sto$
IF sto$ = "a" THEN GOTO 140:  ELSE GOTO 104
104 IF sto$ = "b" THEN GOTO 110:  ELSE GOTO 106
106 PRINT "That's not an option. Make sure your answers are in lowercase."
GOTO 102
110 CLS
PRINT "You walk in to see the mutant storekeeper looking at you."
LOCATE 14, 55
PRINT "|Hello, Dirk. Can I "
LOCATE 15, 55
PRINT "|help you?"
CIRCLE (319, 239), 100, 14  'head
PAINT (320, 240), 14, 14
CIRCLE (269, 189), 18, 15  'eye
PAINT (270, 190), 15, 15
CIRCLE (269, 189), 8, 0  'pupil
PAINT (268, 188), 0, 0
CIRCLE (369, 289), 18, 15  'eye
PAINT (370, 290), 15, 15
CIRCLE (369, 289), 8, 0  'pupil
PAINT (368, 288), 0, 0
CIRCLE (319, 269), 20, 0
PAINT (320, 270), 0, 0'mouth
LOCATE 28, 1
PRINT "|Well what do you have?| you asked."
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
PRINT "|Here is our selections|"   'B STORE SELECTIONS
PRINT "(a) = Inflatible tent"
PRINT "(b) = 9ft bar of plutonium"
PRINT "(c) = small little knife"
PRINT "(d) = Inflatible moutain top mansion"
PRINT "(e) = Propane BBQ"
PRINT
112 INPUT "Which item do you wish to have"; hv$
IF hv$ = "a" THEN PRINT "Here ya go. Enjoy.";  ELSE GOTO 113
113 IF hv$ = "b" THEN PRINT "Well enjoy.";  ELSE GOTO 114
114 IF hv$ = "c" THEN PRINT "Well don't cut yer self.";  ELSE GOTO 115
115 IF hv$ = "d" THEN PRINT "I think that costs a little more than you have.";  ELSE GOTO 116
116 IF hv$ = "e" THEN PRINT "Have fun and don't cook any cows!";  ELSE GOTO 117
117 IF hv$ = "" THEN GOTO 112
PRINT "Here is some more stuff we have."
PRINT "(f) = Speed boat"
PRINT "(g) = Pin"
PRINT "(h) = Bottle w/note"
PRINT "(i) = Home Video Library"
PRINT "(j) = Squrting pen"
PRINT
118 INPUT "Which of these items do you want"; sho$
IF sho$ = "f" THEN PRINT "Sorry. You can't afford that one.";  ELSE GOTO 119
119 IF sho$ = "g" THEN PRINT "Okay. Here ya go.";  ELSE GOTO 120
120 IF sho$ = "h" THEN PRINT "Wow! Don't die or nothing with that.";  ELSE GOTO 121
121 IF sho$ = "i" THEN PRINT "Hours of fun in your hands.";  ELSE GOTO 122
122 IF sho$ = "j" THEN PRINT "Becareful, not to aim it at my eye.";  ELSE GOTO 123
123 IF sho$ = "" THEN GOTO 118
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
129 PRINT "You walk back to your mobile."
PRINT "Now which two planets do you wish to go?"    'TWO PLANETS
LINE (100, 80)-(600, 450), 12, B
LINE (101, 81)-(599, 449), 12, B
LOCATE 17, 25
PRINT "You are here (XSC)"
CIRCLE (320, 240), 6, 15
CIRCLE (320, 240), 5, 11
CIRCLE (320, 240), 4, 9
CIRCLE (320, 240), 3, 1
LOCATE 17, 34
LOCATE 7, 16
PRINT "-A- Numinos"
LOCATE 17, 22
CIRCLE (179, 129), 6, 5
PAINT (180, 130), 5, 5
CIRCLE (429, 359), 6, 13
PAINT (430, 360), 13, 13
LOCATE 22, 50
PRINT "-B- (Unknown)"
LOCATE 30, 1
130 INPUT "Which letter do you wish to choose (a/b)"; abc$
IF abc$ = "a" THEN GOTO 210:  ELSE GOTO 131
131 IF abc$ = "b" THEN GOTO 300:  ELSE GOTO 132
132 PRINT "That is not an option. All answers must be in lower case."
GOTO 130
140 CLS
PRINT "You walk in and see oodles of food. Then an odd"
PRINT "store worker comes up."
LOCATE 14, 50
CIRCLE (319, 239), 100, 14  'head
PAINT (320, 240), 14, 14
CIRCLE (269, 189), 18, 15  'eye
PAINT (270, 190), 15, 15
CIRCLE (269, 189), 8, 0  'pupil
PAINT (268, 188), 0, 0
CIRCLE (369, 189), 18, 15  'eye
PAINT (370, 190), 15, 15
CIRCLE (369, 189), 8, 0  'pupil
PAINT (368, 188), 0, 0
CIRCLE (319, 269), 20, 0
PAINT (320, 270), 0, 0'mouth
PRINT "|Hello, may I help you?"
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
PRINT " |Yes. Do you have a jar of lithium?| you ask."
PRINT "| Sorry, but we don't.|"
PRINT "As you leave the store. the other two stores begin to close."
GOTO 129
210 CLS
PRINT "You set your destination in your computer and zoom off to Numinos..."
CIRCLE (270, 250), 55, 15 'cockpit
LINE (179, 259)-(360, 320), 2, B 'ship body
PAINT (180, 260), 2, 2
CIRCLE (279, 239), 16, 14 'head
PAINT (280, 240), 14, 14
LINE (155, 250)-(55, 250), 15
LINE (150, 300)-(45, 300), 15
LOCATE 18, 5
PRINT "***ZOOOM!***"
LOCATE 25, 1
INPUT "Press ENTER"; en$
CLS
212 PRINT "You are now in orbit of the strange red type planet."
CIRCLE (639, 479), 400, 4                        'landing #1
PAINT (638, 478), 4, 4
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (220, 240), 2      'ship, moon, planet
PSET (221, 240), 2
PSET (222, 240), 2
FOR freq = 1600 TO 1400 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange red type planet."
CIRCLE (639, 479), 400, 4
PAINT (638, 478), 4, 4
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (240, 245), 2      'ship, moon, planet
PSET (241, 245), 2
PSET (242, 245), 2
FOR freq = 1400 TO 1200 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange red type planet."
CIRCLE (639, 479), 400, 4
PAINT (638, 478), 4, 4
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (260, 255), 2      'ship, moon, planet
PSET (261, 255), 2
PSET (262, 255), 2
FOR freq = 1200 TO 1000 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange red type planet."
CIRCLE (639, 479), 400, 4
PAINT (638, 478), 4, 4
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (280, 265), 2      'ship, moon, planet
PSET (281, 265), 2
PSET (282, 265), 2
FOR freq = 1000 TO 800 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange red type planet."
CIRCLE (639, 479), 400, 4
PAINT (638, 478), 4, 4
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (300, 275), 2      'ship, moon, planet
PSET (301, 275), 2
PSET (302, 275), 2
FOR freq = 800 TO 600 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange red type planet."
CIRCLE (639, 479), 400, 4
PAINT (638, 478), 4, 4
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (320, 285), 2      'ship, moon, planet
PSET (321, 285), 2
PSET (322, 285), 2
FOR freq = 600 TO 400 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange red type planet."
CIRCLE (639, 479), 400, 4
PAINT (638, 478), 4, 4
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (340, 295), 2      'ship, moon, planet
PSET (341, 295), 2
PSET (342, 295), 2
FOR freq = 400 TO 200 STEP -40
        SOUND freq, 1
NEXT freq
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
218 PRINT "You land on the smooth surface of the planet. You see many kinds"
PRINT "of plantlife everywhere. You're not sure why you're here. "
INPUT "Want to leave and come back later? (y/n)"; lea$     'leave NO YES
IF lea$ = "y" THEN GOTO 220:  ELSE GOTO 225
99 CLS
220
PRINT "Now which three planets do you wish to go?" 'SELECTION #2
LINE (100, 80)-(600, 450), 12, B
LINE (101, 81)-(599, 449), 12, B
CIRCLE (179, 129), 6, 15
CIRCLE (179, 129), 5, 11
CIRCLE (179, 129), 4, 9
CIRCLE (179, 129), 3, 1
LOCATE 17, 34
PRINT "-B- Xen Shopping Center"
CIRCLE (319, 239), 6, 4
PAINT (320, 240), 4, 4
LOCATE 7, 16
PRINT "-A- You are here (Numinos)"
CIRCLE (429, 359), 6, 13
PAINT (430, 360), 13, 13
LOCATE 22, 50
PRINT "-C- (Unknown)"
LOCATE 30, 1
221 INPUT "Which letter do you wish to choose (a/b/c)"; akb$
IF akb$ = "a" THEN GOTO 210:   ELSE GOTO 222
222 IF akb$ = "b" THEN GOTO 100:  ELSE GOTO 223
223 IF akb$ = "c" THEN GOTO 300:  ELSE GOTO 224
224 PRINT "That's not an option"
GOTO 221
225 PRINT "You notice an odd path. You look again and see nothing else."
PRINT "You stroll along, feeling fine. "
PRINT "You come to a big grey building."
CIRCLE (319, 239), 55, 8
PAINT (320, 240), 8, 8
LINE (259, 269)-(499, 319), 8, B
PAINT (260, 270), 8, 8
INPUT "Press ENTER"; en$
PRINT
PRINT "As you walk in a group of odd looking natives jump at you. Now what?"
PRINT "You can't seem to under stand what they are saying? "
IF hv$ = "e" THEN GOTO 235:  ELSE GOTO 228
228 PRINT "They wait for you to cook something, but you don't have anything"
PRINT "to cook with, so you die."
INPUT "Press ENTER"; en$
GOTO 450
235 PRINT "You look in your pocket and see the BBQ you bought. You pull it "
PRINT "out and start cooking some fish. Then smell over powers the natives"
PRINT "and soon they are all out cold. You quickly put back the BBQ in your"
PRINT "pocket and walk into the building."
INPUT "Press ENTER"; en$
CLS
PRINT "You walk in and see a big cow statue in front of you. Its eyes stare"
PRINT "at you."
CIRCLE (159, 239), 25, 12
PAINT (160, 240), 12, 12
CIRCLE (159, 239), 12, 4
PAINT (160, 240), 4, 4
LOCATE 18, 1
PRINT "|Why have you come Dirk?| the cow asks."
PRINT "|I've come to know where the putty thing is headed to|."
PRINT "You go on and you get the info, that the unknown planet is called"
PRINT "Tranvil 1. You hop in your ship, and set your nav computers."
PRINT "You shoot ofward to the strange Tranvil 1 "
INPUT "Press ENTER"; en$
CLS
GOTO 305
CIRCLE (270, 250), 55, 15 'cockpit
LINE (179, 259)-(360, 320), 2, B 'ship body
PAINT (180, 260), 2, 2
CIRCLE (279, 239), 16, 14 'head
PAINT (280, 240), 14, 14
LINE (155, 250)-(55, 250), 15
LINE (150, 300)-(45, 300), 15
LOCATE 18, 5
PRINT "***ZOOOM!***"
LOCATE 25, 1
INPUT "Press ENTER"; en$
GOTO 300
300 CLS
PRINT "You shoot ofward to the strange unknown planet."
CIRCLE (270, 250), 55, 15 'cockpit
LINE (179, 259)-(360, 320), 2, B 'ship body
PAINT (180, 260), 2, 2
CIRCLE (279, 239), 16, 14 'head
PAINT (280, 240), 14, 14
LINE (155, 250)-(55, 250), 15
LINE (150, 300)-(45, 300), 15
LOCATE 18, 5
PRINT "***ZOOOM!***"
LOCATE 25, 1
INPUT "Press ENTER"; en$
CLS
305 PRINT "You are landing now..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (220, 240), 2      'ship, moon, planet
PSET (221, 240), 2
PSET (222, 240), 2
FOR freq = 1600 TO 1400 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are landing now..."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (240, 245), 2      'ship, moon, planet
PSET (241, 245), 2
PSET (242, 245), 2
FOR freq = 1400 TO 1200 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are landing now..."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (260, 255), 2      'ship, moon, planet
PSET (261, 255), 2
PSET (262, 255), 2
FOR freq = 1200 TO 1000 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are landing now..."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (280, 265), 2      'ship, moon, planet
PSET (281, 265), 2
PSET (282, 265), 2
FOR freq = 1000 TO 800 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are landing now..."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (300, 275), 2      'ship, moon, planet
PSET (301, 275), 2
PSET (302, 275), 2
FOR freq = 800 TO 600 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are landing now..."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (320, 285), 2      'ship, moon, planet
PSET (321, 285), 2
PSET (322, 285), 2
FOR freq = 600 TO 400 STEP -40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are landing now..."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (340, 295), 2      'ship, moon, planet
PSET (341, 295), 2
PSET (342, 295), 2
FOR freq = 400 TO 200 STEP -40
        SOUND freq, 1
NEXT freq
CLS
310 PRINT "Your ship touches down and you look for any cities."
PRINT "A strange mutant walks up to you."
CIRCLE (319, 239), 100, 14  'head
PAINT (320, 240), 14, 14
CIRCLE (269, 189), 18, 15  'eye
PAINT (270, 190), 15, 15
CIRCLE (269, 189), 8, 0  'pupil
PAINT (268, 188), 0, 0
CIRCLE (369, 289), 18, 15  'eye
PAINT (370, 290), 15, 15
CIRCLE (369, 289), 8, 0  'pupil
PAINT (368, 288), 0, 0
CIRCLE (319, 269), 20, 0
PAINT (320, 270), 0, 0'mouth
LOCATE 14, 50
PRINT "|Hey. Aren't you Dirk?"
LOCATE 26, 1
PRINT "|Yes I am.| you say."
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
PRINT "The mutant tells you of a shuttle that is headed for the "
PRINT "putty. You must now get onto that shuttle... and fast!"
PRINT
PRINT "You start jogging west, towards the shuttle. Oh no! A guard"
PRINT "sees you! Now what?"
PRINT
CIRCLE (319, 239), 100, 14  'head
PAINT (320, 240), 14, 14
CIRCLE (269, 189), 18, 15  'eye
PAINT (270, 190), 15, 15
CIRCLE (269, 189), 8, 0  'pupil
PAINT (268, 188), 0, 0
CIRCLE (369, 189), 18, 15  'eye
PAINT (370, 190), 15, 15
CIRCLE (369, 189), 8, 0  'pupil
PAINT (368, 188), 0, 0
CIRCLE (319, 269), 20, 0
PAINT (320, 270), 0, 0'mouth
LOCATE 14, 48
PRINT "|Hey! Hold it right there."
LOCATE 15, 48
PRINT "|What are ye doing here?"
LOCATE 22, 1
PRINT "Uh..."
PRINT "(a) = |My dog! Oh my dog ran this way!|"
PRINT "(b) = |Oh what is that?|"
INPUT "Choose a sentence to say."; sen$
IF sen$ = "a" THEN PRINT "I don't think so, jerk.";  ELSE GOTO 315
315 IF sen$ = "b" THEN PRINT "Hmmm.... I'm not falling for that one this time.";  ELSE PRINT "Nice try."
318 PRINT "The ugly guard aims the gun at your face."
IF sho$ = "i" THEN GOTO 325:  ELSE GOTO 320
320 PRINT "He takes a second then fires. "
INPUT "Press ENTER"; en$
GOTO 450
325 PRINT "You look in your pocket and see your Home video library! You pull"
PRINT "that out and he slowly lowers his gun. |Um....| he says. |Can I have"
PRINT "those videos?|"
INPUT "Are you going to give him those"; giv$
IF giv$ = "y" THEN GOTO 340:  ELSE GOTO 328
328 PRINT "|No. You can't have them.| you say."
PRINT "The guard shrugs and shoots you dead. |I'll get them no matter what"
PRINT "you do. Ha ha ha.| He grabs the videos out of your hand and walks off."
INPUT "Press ENTER"; en$
GOTO 450
340 PRINT "|Oh.. Okay. You can have them.| you say."
PLAY "L5 > A."
PRINT "The guard runs off and watches them and then dies when his heart gets"
PRINT "bored of watching 72 videos showing cheese melting in the winter sun."
INPUT "Press ENTER"; en$
341 CLS
PAINT (1, 1), 9, 9
LINE (269, 159)-(350, 420), 15, B
PAINT (270, 160), 15, 15
CIRCLE (309, 139), 48, 15
PAINT (310, 140), 15, 15
LINE (289, 159)-(330, 420), 4, B
PAINT (290, 160), 4, 4
LINE (1, 420)-(680, 480), 10, B
PAINT (2, 421), 10, 10
PSET (120, 419), 0
PSET (120, 418), 0
PSET (120, 417), 0
PSET (120, 416), 0
PSET (120, 415), 0
PLAY "< < < < B"
PRINT "You hop into the rocket and it shoots off towards the putty."
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
PRINT "You leave the planet..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
CIRCLE (99, 389), 25, 3
PAINT (100, 390), 3, 3
PSET (340, 290), 2      'ship, moon, planet, putty
PSET (341, 290), 2
PSET (342, 290), 2
FOR freq = 200 TO 400 STEP 40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You leave the planet..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
CIRCLE (99, 389), 30, 3
PAINT (100, 390), 3, 3
PSET (320, 280), 2      'ship, moon, planet, putty
PSET (321, 280), 2
PSET (322, 280), 2
FOR freq = 400 TO 600 STEP 40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You leave the planet..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
CIRCLE (99, 389), 35, 3
PAINT (100, 390), 3, 3
PSET (300, 270), 2      'ship, moon, planet, putty
PSET (301, 270), 2
PSET (302, 270), 2
FOR freq = 600 TO 800 STEP 40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You leave the planet..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
CIRCLE (99, 389), 40, 3
PAINT (100, 390), 3, 3
PSET (280, 260), 2      'ship, moon, planet, putty
PSET (281, 260), 2
PSET (282, 260), 2
FOR freq = 800 TO 1000 STEP 40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You leave the planet..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
CIRCLE (99, 389), 38, 3
PAINT (100, 390), 3, 3
PSET (260, 265), 2      'ship, moon, planet, putty
PSET (261, 265), 2
PSET (262, 265), 2
FOR freq = 1000 TO 1200 STEP 40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You leave the planet..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
CIRCLE (99, 389), 36, 3
PAINT (100, 390), 3, 3
PSET (240, 270), 2      'ship, moon, planet, putty
PSET (241, 270), 2
PSET (242, 270), 2
FOR freq = 1200 TO 1400 STEP 40
        SOUND freq, 1
NEXT freq
CLS
PRINT "You leave the planet..."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
CIRCLE (99, 389), 30, 3
PAINT (100, 390), 3, 3
PSET (220, 260), 2      'ship, moon, planet, putty
PSET (221, 260), 2
PSET (222, 260), 2
FOR freq = 1400 TO 1600 STEP 40
        SOUND freq, 1
NEXT freq
INPUT "Press ENTER"; en$
345 CLS
PRINT "You can see the putty now on your radar."
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (289, 229), 6, 4
PAINT (290, 230), 4, 4
LOCATE 30, 1
INPUT "Press ENTER"; en$
350 CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (295, 239), 6, 4
PAINT (296, 240), 4, 4
PLAY "L5 B."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (299, 239), 6, 4
PAINT (300, 240), 4, 4
PLAY "C."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (306, 239), 6, 4
PAINT (307, 240), 4, 4
PLAY "B."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (309, 239), 6, 4
PAINT (310, 240), 4, 4
PLAY "C."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (319, 239), 6, 4
PAINT (320, 240), 4, 4
PLAY "B."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (319, 239), 6, 4
PAINT (320, 240), 4, 4
PLAY "C."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (319, 239), 8, 4
PAINT (320, 240), 4, 4
PLAY "B."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (319, 239), 12, 4
PAINT (320, 240), 4, 4
PLAY "C."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (319, 239), 18, 4
PAINT (320, 240), 4, 4
PLAY "B."
CLS
PRINT "Now what? It's heading into your direction!"
CIRCLE (320, 240), 280, 2
CIRCLE (320, 240), 180, 2
CIRCLE (320, 240), 80, 2
CIRCLE (320, 240), 10, 2
CIRCLE (319, 239), 22, 4
PAINT (320, 240), 4, 4
PLAY "C."
CLS
PRINT "AHHH! Now what? It's moving very fast!"
PRINT "Let's sort out your options."
PRINT "(a) = Zoom around it."
PRINT "(b) = Shoot at it"
PRINT "(c) = Ram into it."
PRINT
352 INPUT "Which choice do you want to choose"; cuh$
IF cuh$ = "a" THEN GOTO 362:  ELSE GOTO 353
353 IF cuh$ = "b" THEN GOTO 372:  ELSE GOTO 355
355 IF cuh$ = "c" THEN GOTO 382:  ELSE GOTO 356
356 PRINT "That choice won't work here!"
362 CLS
PRINT "You hang a sharp turn and into the side of the putty. You can't "
PRINT "pull out of the putty and slowly are sucked in. It get's brighter"
PRINT "And then everything is so bright you close your eyes shut! Then"
PRINT "You burn up."
INPUT "Press ENTER"; en$
365 CLS
PLAY "L5 A."
CLS
PAINT (1, 1), 8
PLAY "> A."
CLS
PAINT (1, 1), 7
PLAY "> > A."
CLS
PAINT (1, 1), 15
PLAY "> > A."
GOTO 450
372 CLS
PRINT "You press the firing button, but nothing comes out. It's empty!"
PRINT "Of all the luck in Ireland! Too late now! Your doomed into the "
PRINT "bright center of the putty."
INPUT "Press ENTER"; en$
GOTO 365
382 PRINT "You set the main sheilds to the max and punch the throttle!"
INPUT "Press ENTER"; en$
CLS
CIRCLE (129, 379), 68, 3
PAINT (130, 380), 3, 3
PSET (280, 380), 15
PSET (281, 380), 15
PSET (283, 380), 15
PLAY "L4 C+"
CLS
CIRCLE (129, 379), 70, 3
PAINT (130, 380), 3, 3
PSET (270, 380), 15
PSET (271, 380), 15
PSET (273, 380), 15
PLAY "L4 A+"
CLS
CIRCLE (129, 379), 72, 3
PAINT (130, 380), 3, 3
PSET (260, 380), 15
PSET (261, 380), 15
PSET (263, 380), 15
PLAY "L5 C+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
PSET (250, 380), 15
PSET (251, 380), 15
PSET (253, 380), 15
PLAY "L5 A+"
CLS
CIRCLE (129, 379), 72, 3
PAINT (130, 380), 3, 3
PSET (240, 380), 15
PSET (241, 380), 15
PSET (243, 380), 15
PLAY "L6 C+"
CLS
CIRCLE (129, 379), 70, 3
PAINT (130, 380), 3, 3
PSET (210, 380), 15
PSET (211, 380), 15
PSET (213, 380), 15
PLAY "L6 A+"
CLS
CIRCLE (129, 379), 68, 3
PAINT (130, 380), 3, 3
PSET (190, 380), 15
PSET (191, 380), 15
PSET (193, 380), 15
PLAY "L7 C+"
CLS
CIRCLE (129, 379), 66, 3
PAINT (130, 380), 3, 3
PSET (170, 380), 15
PSET (171, 380), 15
PSET (173, 380), 15
PLAY "L7 A+"
CLS
CIRCLE (129, 379), 64, 3
PAINT (130, 380), 3, 3
PSET (160, 380), 15
PSET (161, 380), 15
PSET (163, 380), 15
PLAY "L8 C+"
CLS
CIRCLE (129, 379), 66, 3
PAINT (130, 380), 3, 3
PLAY "L8 A+"
CLS
CIRCLE (129, 379), 68, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 24, 11
PAINT (130, 380), 11, 11
PLAY "L8 C+"
CLS
CIRCLE (129, 379), 70, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 24, 3
PAINT (130, 380), 3, 3
PLAY "L9 A+"
CLS
CIRCLE (129, 379), 72, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 32, 11
PAINT (130, 380), 11, 11
PLAY "L9 C+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 24, 3
PAINT (130, 380), 3, 3
PLAY "L10 A+"
CLS
CIRCLE (129, 379), 72, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 44, 11
PAINT (130, 380), 11, 11
PLAY "L10 C+"
CLS
CIRCLE (129, 379), 70, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 24, 3
PAINT (130, 380), 3, 3
PLAY "L11 A+"
CLS
CIRCLE (129, 379), 68, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 52, 11
PAINT (130, 380), 11, 11
PLAY "L11 C+"
CLS
CIRCLE (129, 379), 66, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 24, 3
PAINT (130, 380), 3, 3
PLAY "L12 A+"
CLS
CIRCLE (129, 379), 64, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 66, 11
PAINT (130, 380), 11, 11
PLAY "L12 C+"
CLS
CIRCLE (129, 379), 66, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 24, 3
PAINT (130, 380), 3, 3
PLAY "L13 A+"
CLS
CIRCLE (129, 379), 68, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 78, 11
PAINT (130, 380), 11, 11
PLAY "L13 C+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 89, 11
PAINT (130, 380), 11, 11
PLAY "L14 A+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 110, 11
PAINT (130, 380), 11, 11
PLAY "L15 C+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 136, 11
PAINT (130, 380), 11, 11
PLAY "L16 A+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 162, 11
PAINT (130, 380), 11, 11
PSET (300, 380), 15
PSET (301, 380), 15
PSET (302, 380), 15
PLAY "L18 C+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 184, 11
PAINT (130, 380), 11, 11
PSET (330, 380), 15
PSET (329, 380), 15
PSET (328, 380), 15
PLAY "L20 A+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 200, 11
PAINT (130, 380), 11, 11
PSET (360, 380), 15
PSET (359, 380), 15
PSET (358, 380), 15
PLAY "L22 C+"
CLS
CIRCLE (129, 379), 74, 3
PAINT (130, 380), 3, 3
CIRCLE (129, 379), 230, 11
PAINT (130, 380), 11, 11
PSET (390, 380), 15
PSET (389, 380), 15
PSET (388, 380), 15
PLAY "L24 A+"
CLS
CIRCLE (129, 379), 255, 11
PAINT (130, 380), 11, 11
PSET (420, 380), 15
PSET (419, 380), 15
PSET (418, 380), 15
PLAY "L24 C+"
CLS
CIRCLE (129, 379), 282, 11
PAINT (130, 380), 11, 11
PSET (490, 380), 15
PSET (489, 380), 15
PSET (488, 380), 15
PLAY "L24 A+"
CLS
PRINT "You zoomed out of the explosion and land onto Tranvil 1"
FOR freq = 600 TO 1800 STEP 20
        SOUND freq, 1
NEXT freq
CLS
PRINT "You won"
PLAY "L16 < B. > >"
CLS
PRINT "  You won"
PLAY "C"
CLS
PRINT "    You won"
PLAY "D."
CLS
PRINT "       You won"
PLAY "C#"
CLS
PRINT "              You won"
PLAY "D."
PLAY "C# D. C# D. L4 D"
PRINT "     You won          You won"
PLAY "L16 E. < B > "
PRINT "    You won     You won          You won        You won"
PLAY "L4 C L16 D. < A L4 B"
PRINT " You won                You won          You won"
PLAY "L16 G. A B. A# B. A#"
PRINT "  You won                You won"
PLAY "L4 B L16 A. G G."
PRINT "         You won          You won                  You won"
PLAY "F# F#. A G. E L4 D"
INPUT "Press ENTER"; en$
CLS
PAINT (1, 1), 9
CIRCLE (319, 239), 120, 4
PAINT (320, 240), 4, 4
CIRCLE (319, 239), 100, 12
PAINT (320, 240), 12, 12
CIRCLE (319, 239), 76, 14
PAINT (320, 240), 14, 14
LINE (1, 269)-(640, 480), 10, B
PAINT (2, 270), 10, 10
LOCATE 26, 1
PRINT "People look at the sky and see a clear blue or grey, or greenish,"
PRINT "where ever you're from and rejoice in the destruction of the blob!"
PRINT "Now you end your quest in this galaxy, and head onward towards"
PRINT "Fortunius..."
PRINT ""
INPUT "Press ENTER"; en$
380 CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (1, 220), 2
PSET (2, 220), 2
PSET (3, 220), 2
PSET (4, 220), 2
PLAY "L8   A"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (11, 220), 2
PSET (12, 220), 2
PSET (13, 220), 2
PSET (14, 220), 2
PLAY "L8 C"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (22, 220), 2
PSET (23, 220), 2
PSET (24, 220), 2
PSET (25, 220), 2
PLAY "L8 A"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (33, 220), 2
PSET (34, 220), 2
PSET (35, 220), 2
PSET (36, 220), 2
PLAY "L8 C"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (51, 220), 2
PSET (52, 220), 2
PSET (53, 220), 2
PSET (54, 220), 2
PLAY "L9 A "
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (71, 220), 2
PSET (72, 220), 2
PSET (73, 220), 2
PSET (74, 220), 2
PLAY "L10 C "
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (111, 220), 2
PSET (112, 220), 2
PSET (113, 220), 2
PSET (114, 220), 2
PLAY "L12 A"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (133, 220), 2
PSET (134, 220), 2
PSET (135, 220), 2
PSET (136, 220), 2
PLAY "L12 C"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
PSET (151, 220), 2
PSET (152, 220), 2
PSET (153, 220), 2
PSET (154, 220), 2
PLAY "L12 A"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (165, 220)-(221, 220), 2
PSET (159, 220), 2
PSET (162, 220), 2
PSET (157, 220), 2
PSET (161, 220), 2
PLAY "L12 C"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (172, 220)-(248, 220), 2
PSET (163, 220), 2
PSET (165, 220), 2
PSET (169, 220), 2
PSET (168, 220), 2
PLAY "L12 A"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (201, 220)-(342, 220), 2
PSET (195, 220), 2
PSET (182, 220), 2
PSET (186, 220), 2
PLAY "L12 C"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (262, 220)-(431, 220), 2
PSET (242, 220), 2
PSET (245, 220), 2
PSET (259, 220), 2
PLAY "L12 A"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (362, 220)-(456, 220), 2
PSET (293, 220), 2
PSET (285, 220), 2
PSET (288, 220), 2
PLAY "L12 C"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (461, 220)-(589, 220), 2
PSET (355, 220), 2
PSET (342, 220), 2
PSET (346, 220), 2
PLAY "L12 A"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (546, 220)-(640, 220), 2
PSET (395, 220), 2
PSET (381, 220), 2
PSET (426, 220), 2
PLAY "L12 C"
CLS
CIRCLE (319, 469), 120, 13
PAINT (320, 470), 13, 13
CIRCLE (629, 49), 72, 4
PAINT (630, 50), 4, 4
CIRCLE (629, 49), 58, 12
PAINT (630, 50), 12, 12
CIRCLE (629, 49), 42, 14
PAINT (630, 50), 14, 14
LINE (623, 220)-(680, 220), 2
PSET (595, 220), 2
PSET (582, 220), 2
PSET (586, 220), 2
PLAY "L12 A"
CLS
FOR freq = 200 TO 1400 STEP 10
        SOUND freq, 1
NEXT freq
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT "                  THE"
PRINT
PRINT
PRINT
PRINT "                       END"
GOTO 455
INPUT "Press ENTER"; en$
450 CLS
PRINT "You've died. Oh well. "
INPUT "      WOULD YOU LIKE TO PLAY AGAIN (y/n)"; pla$
IF pla$ = "y" THEN GOTO 10:  ELSE GOTO 451
451 IF pla$ = "Y" THEN GOTO 10:  ELSE GOTO 453
453 PRINT "Oh well. "
PRINT
 PRINT "Try me again soon!"
455 PRINT "THANKS FOR PLAYING DIRK GIRKLIN!"
PRINT "TRY ME AGAIN SOON!"
END




