SCREEN 12 'BEGINING
10 CLS
LINE (100, 180)-(480, 260), 1, B
LINE (101, 181)-(479, 259), 1, B
LINE (102, 182)-(478, 258), 1, B
LINE (103, 183)-(477, 257), 9, B
LINE (104, 184)-(476, 256), 9, B
LINE (105, 185)-(475, 255), 9, B
LINE (106, 186)-(474, 254), 11, B
LINE (107, 187)-(473, 253), 11, B
LINE (108, 188)-(472, 252), 11, B
LINE (109, 189)-(471, 251), 15, B
LINE (110, 190)-(470, 250), 15, B
LINE (111, 191)-(469, 249), 15, B
LINE (112, 192)-(468, 248), 7, B
LINE (113, 193)-(467, 247), 7, B
LINE (114, 194)-(466, 246), 7, B
LINE (115, 195)-(465, 245), 8, B
LINE (116, 196)-(464, 244), 8, B
LINE (117, 197)-(463, 243), 8, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "L16 D"
CLS
LINE (100, 180)-(480, 260), 8, B
LINE (101, 181)-(479, 259), 1, B
LINE (102, 182)-(478, 258), 1, B
LINE (103, 183)-(477, 257), 1, B
LINE (104, 184)-(476, 256), 9, B
LINE (105, 185)-(475, 255), 9, B
LINE (106, 186)-(474, 254), 9, B
LINE (107, 187)-(473, 253), 11, B
LINE (108, 188)-(472, 252), 11, B
LINE (109, 189)-(471, 251), 11, B
LINE (110, 190)-(470, 250), 15, B
LINE (111, 191)-(469, 249), 15, B
LINE (112, 192)-(468, 248), 15, B
LINE (113, 193)-(467, 247), 7, B
LINE (114, 194)-(466, 246), 7, B
LINE (115, 195)-(465, 245), 7, B
LINE (116, 196)-(464, 244), 8, B
LINE (117, 197)-(463, 243), 8, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "E"
CLS
LINE (100, 180)-(480, 260), 8, B
LINE (101, 181)-(479, 259), 8, B
LINE (102, 182)-(478, 258), 1, B
LINE (103, 183)-(477, 257), 1, B
LINE (104, 184)-(476, 256), 1, B
LINE (105, 185)-(475, 255), 9, B
LINE (106, 186)-(474, 254), 9, B
LINE (107, 187)-(473, 253), 9, B
LINE (108, 188)-(472, 252), 11, B
LINE (109, 189)-(471, 251), 11, B
LINE (110, 190)-(470, 250), 11, B
LINE (111, 191)-(469, 249), 15, B
LINE (112, 192)-(468, 248), 15, B
LINE (113, 193)-(467, 247), 15, B
LINE (114, 194)-(466, 246), 7, B
LINE (115, 195)-(465, 245), 7, B
LINE (116, 196)-(464, 244), 7, B
LINE (117, 197)-(463, 243), 8, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "F"
CLS
LINE (100, 180)-(480, 260), 8, B
LINE (101, 181)-(479, 259), 8, B
LINE (102, 182)-(478, 258), 8, B
LINE (103, 183)-(477, 257), 1, B
LINE (104, 184)-(476, 256), 1, B
LINE (105, 185)-(475, 255), 1, B
LINE (106, 186)-(474, 254), 9, B
LINE (107, 187)-(473, 253), 9, B
LINE (108, 188)-(472, 252), 9, B
LINE (109, 189)-(471, 251), 11, B
LINE (110, 190)-(470, 250), 11, B
LINE (111, 191)-(469, 249), 11, B
LINE (112, 192)-(468, 248), 15, B
LINE (113, 193)-(467, 247), 15, B
LINE (114, 194)-(466, 246), 15, B
LINE (115, 195)-(465, 245), 7, B
LINE (116, 196)-(464, 244), 7, B
LINE (117, 197)-(463, 243), 7, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "G#"
CLS
LINE (100, 180)-(480, 260), 7, B
LINE (101, 181)-(479, 259), 8, B
LINE (102, 182)-(478, 258), 8, B
LINE (103, 183)-(477, 257), 8, B
LINE (104, 184)-(476, 256), 1, B
LINE (105, 185)-(475, 255), 1, B
LINE (106, 186)-(474, 254), 1, B
LINE (107, 187)-(473, 253), 9, B
LINE (108, 188)-(472, 252), 9, B
LINE (109, 189)-(471, 251), 9, B
LINE (110, 190)-(470, 250), 11, B
LINE (111, 191)-(469, 249), 11, B
LINE (112, 192)-(468, 248), 11, B
LINE (113, 193)-(467, 247), 15, B
LINE (114, 194)-(466, 246), 15, B
LINE (115, 195)-(465, 245), 15, B
LINE (116, 196)-(464, 244), 7, B
LINE (117, 197)-(463, 243), 7, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "A"
CLS
LINE (100, 180)-(480, 260), 7, B
LINE (101, 181)-(479, 259), 7, B
LINE (102, 182)-(478, 258), 8, B
LINE (103, 183)-(477, 257), 8, B
LINE (104, 184)-(476, 256), 8, B
LINE (105, 185)-(475, 255), 1, B
LINE (106, 186)-(474, 254), 1, B
LINE (107, 187)-(473, 253), 1, B
LINE (108, 188)-(472, 252), 9, B
LINE (109, 189)-(471, 251), 9, B
LINE (110, 190)-(470, 250), 9, B
LINE (111, 191)-(469, 249), 11, B
LINE (112, 192)-(468, 248), 11, B
LINE (113, 193)-(467, 247), 11, B
LINE (114, 194)-(466, 246), 15, B
LINE (115, 195)-(465, 245), 15, B
LINE (116, 196)-(464, 244), 15, B
LINE (117, 197)-(463, 243), 7, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "G#"
CLS
LINE (100, 180)-(480, 260), 7, B
LINE (101, 181)-(479, 259), 7, B
LINE (102, 182)-(478, 258), 7, B
LINE (103, 183)-(477, 257), 8, B
LINE (104, 184)-(476, 256), 8, B
LINE (105, 185)-(475, 255), 8, B
LINE (106, 186)-(474, 254), 1, B
LINE (107, 187)-(473, 253), 1, B
LINE (108, 188)-(472, 252), 1, B
LINE (109, 189)-(471, 251), 9, B
LINE (110, 190)-(470, 250), 9, B
LINE (111, 191)-(469, 249), 9, B
LINE (112, 192)-(468, 248), 11, B
LINE (113, 193)-(467, 247), 11, B
LINE (114, 194)-(466, 246), 11, B
LINE (115, 195)-(465, 245), 15, B
LINE (116, 196)-(464, 244), 15, B
LINE (117, 197)-(463, 243), 15, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "F"
CLS
LINE (100, 180)-(480, 260), 15, B
LINE (101, 181)-(479, 259), 7, B
LINE (102, 182)-(478, 258), 7, B
LINE (103, 183)-(477, 257), 7, B
LINE (104, 184)-(476, 256), 8, B
LINE (105, 185)-(475, 255), 8, B
LINE (106, 186)-(474, 254), 8, B
LINE (107, 187)-(473, 253), 1, B
LINE (108, 188)-(472, 252), 1, B
LINE (109, 189)-(471, 251), 1, B
LINE (110, 190)-(470, 250), 9, B
LINE (111, 191)-(469, 249), 9, B
LINE (112, 192)-(468, 248), 9, B
LINE (113, 193)-(467, 247), 11, B
LINE (114, 194)-(466, 246), 11, B
LINE (115, 195)-(465, 245), 11, B
LINE (116, 196)-(464, 244), 15, B
LINE (117, 197)-(463, 243), 15, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "E"
CLS
LINE (100, 180)-(480, 260), 15, B
LINE (101, 181)-(479, 259), 15, B
LINE (102, 182)-(478, 258), 7, B
LINE (103, 183)-(477, 257), 7, B
LINE (104, 184)-(476, 256), 7, B
LINE (105, 185)-(475, 255), 8, B
LINE (106, 186)-(474, 254), 8, B
LINE (107, 187)-(473, 253), 8, B
LINE (108, 188)-(472, 252), 1, B
LINE (109, 189)-(471, 251), 1, B
LINE (110, 190)-(470, 250), 1, B
LINE (111, 191)-(469, 249), 9, B
LINE (112, 192)-(468, 248), 9, B
LINE (113, 193)-(467, 247), 9, B
LINE (114, 194)-(466, 246), 11, B
LINE (115, 195)-(465, 245), 11, B
LINE (116, 196)-(464, 244), 11, B
LINE (117, 197)-(463, 243), 15, B
LOCATE 14, 22
PRINT "HAPPY TOWNE PROGRAMMING INC."
LOCATE 15, 31
PRINT "Presents..."
PLAY "D"
PLAY "E F G# A G# F E D E F G# A G# F E L6 A."
CLS
CLS
CIRCLE (319, 239), 2, 8
PAINT (320, 240), 8, 8
PLAY "L18 < B. >"
CLS
CIRCLE (319, 239), 4, 7
PAINT (320, 240), 7, 7
PLAY " C "
CLS
CIRCLE (319, 239), 8, 15
PAINT (320, 240), 15, 15
PLAY "D."
CLS
CIRCLE (319, 239), 14, 12
PAINT (320, 240), 12, 12
PLAY "C#"
CLS
CIRCLE (319, 239), 20, 4
PAINT (320, 240), 4, 4
PLAY "< B >"
CLS
CIRCLE (319, 239), 26, 6
PAINT (320, 240), 6, 6
PLAY "C#"
CLS
CIRCLE (319, 239), 32, 8
PAINT (320, 240), 8, 8
PLAY "E"
CLS
CIRCLE (319, 239), 40, 7
PAINT (320, 240), 7, 7
LOCATE 14, 35
PRINT "DI"
PLAY "< A"
CLS
CIRCLE (319, 239), 50, 15
PAINT (320, 240), 15, 15
LOCATE 14, 35
PRINT "DIRK"
PLAY "L4 F"
CLS
CIRCLE (319, 239), 62, 11
PAINT (320, 240), 11, 11
LOCATE 14, 35
PRINT "DIRK G"
PLAY "L16 E."
CLS
CIRCLE (319, 239), 75, 9
PAINT (320, 240), 9, 9
LOCATE 14, 35
PRINT "DIRK GIR"
PLAY "C#"
CLS
CIRCLE (319, 239), 100, 1
PAINT (320, 240), 1, 1
LOCATE 14, 35
PRINT "DIRK  GIRKL"
PLAY "L6 A "
CLS
CIRCLE (319, 239), 120, 13
PAINT (320, 240), 13, 13
LOCATE 14, 35
PRINT "DIRK GIRKLIN"
BEEP
CLS
CIRCLE (319, 239), 120, 13
PAINT (320, 240), 13, 13
LOCATE 14, 35
PRINT "DIRK GIRKLIN"
LOCATE 16, 28
PRINT "THE LIQUID ARMPIT PUTTY"
LOCATE 30, 1
INPUT "Press ENTER"; en$
PLAY ">"
11 CLS
LOCATE 3, 32
PRINT "***********"
LOCATE 4, 33
PRINT "MAIN MENU"      'MENU
LOCATE 5, 32
PRINT "***********"
PRINT
PRINT
PRINT
PRINT
PRINT "                 (1) TITLE"
PRINT
PRINT "                 (2) INTRODUCTION"
PRINT
PRINT "                 (3) GAME"
PRINT
PRINT "                 (4) CREDITS"
PRINT
PRINT "              CTRL BREAK TO EXIT "
PRINT
12 INPUT "Which number do wish to choose"; num!
IF num! = 1 THEN GOTO 10:  ELSE GOTO 13
13 IF num! = 2 THEN GOTO 40:  ELSE GOTO 14
14 IF num! = 3 THEN GOTO 60:  ELSE GOTO 15
15 IF num! = 4 THEN GOTO 20:  ELSE GOTO 16
16 PRINT "Invalid selection"
GOTO 11                       'CREDITS
20 CLS
LOCATE 4, 28
PRINT "  CREDITS"
PRINT "            GRAPHICS BY-------GARY BURT"
PRINT "              PROGRAMMER--------GARY BURT"
PRINT "                STORY BY----------GARY BURT"
PRINT "  EVERYTHING ELSE BY------------GARY BURT"
PRINT
PRINT "         ****SPECIAL THANKS TO****"
PRINT "      HAPPY  TOWNE  PROGRAMMING  INC."
LOCATE 30, 25
INPUT "Press ENTER"; en$
GOTO 11
40 CLS
PRINT
PRINT "Long ago... On the planet Fortunius, a strange experiment is begining."
CIRCLE (320, 240), 110, 15
CIRCLE (319, 239), 109, 7
CIRCLE (318, 238), 108, 9
CIRCLE (317, 237), 107, 1
CIRCLE (315, 235), 105, 1             'INTRODUCTION
LOCATE 30, 5
INPUT "Press ENTER"; en$
CLS
BEEP
PLAY "< < < < B < C+"
BEEP
PRINT
PRINT
PRINT "A suden explosion echoed through the planet. Then over time the"
PRINT "planet began to melt. Then a huge ugly ooze formed. It grabbed"
PRINT "all organic life on Fortunius and it came to life. Now 1000 years"
PRINT "later an odd liquid has been eating planets. And nothing has been"
PRINT "been able to stop it..."
PRINT
PRINT
PRINT
LINE (1, 240)-(640, 240), 2
PRINT
PRINT "We leave Dirk shopping for a nifty warp engine at Stud's Engines."
LOCATE 28, 1
INPUT "Press ENTER"; en$          'GAME
GOTO 11
60 CLS
PRINT "  |  How much for this Ace Warp Engine?|, you ask."
PRINT
PRINT "  |  Only 9100.98 Creds.|, says the shopkeeper."
PRINT
PRINT " Dirk looks in horror at the price tag! It was alot. He turned"
PRINT "and strolled off out to his green spacemobile."
PRINT
CIRCLE (270, 250), 55, 15 'cockpit
LINE (179, 259)-(360, 320), 2, B 'ship body
PAINT (180, 260), 2, 2
CIRCLE (279, 239), 16, 14 'head
PAINT (280, 240), 14, 14
LINE (155, 250)-(55, 250), 15
LINE (150, 300)-(45, 300), 15
LOCATE 18, 5
PRINT "***ZOOOM!***"
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
68 PRINT
PRINT "Now which three planets do you wish to go?" 'GRAPH SELECTION #1
LINE (100, 80)-(600, 450), 12, B
LINE (101, 81)-(599, 449), 12, B
CIRCLE (320, 240), 6, 15
CIRCLE (320, 240), 5, 11
CIRCLE (320, 240), 4, 9
CIRCLE (320, 240), 3, 1
LOCATE 17, 34
PRINT "-B- You are here.(Xen Shopping Center)"
CIRCLE (179, 129), 6, 4
PAINT (180, 130), 4, 4
LOCATE 7, 16
PRINT "-A- Numinos"
CIRCLE (429, 359), 6, 13
PAINT (430, 360), 13, 13
LOCATE 22, 50
PRINT "-C- (Unknown)"
LOCATE 30, 1
70 INPUT "Which letter do you wish to choose (a/b/c)"; acb$
IF acb$ = "a" THEN GOTO 90:   ELSE GOTO 72
72 IF acb$ = "b" THEN GOTO 200:  ELSE GOTO 74
74 IF acb$ = "c" THEN GOTO 300:  ELSE GOTO 76
76 PRINT "That is not an option. All answers must be in lower case."
GOTO 70
90 CLS
PRINT "You set your destination in your computer and zoom off to "   'SELECTION A
PRINT "Numinos..."
CIRCLE (270, 250), 55, 15 'cockpit
LINE (179, 259)-(360, 320), 2, B 'ship body
PAINT (180, 260), 2, 2
CIRCLE (279, 239), 16, 14 'head
PAINT (280, 240), 14, 14
LINE (155, 250)-(55, 250), 15
LINE (150, 300)-(45, 300), 15
LOCATE 18, 5
PRINT "***ZOOOM!***"
LOCATE 25, 1
INPUT "Press ENTER"; en$
CLS
92 PRINT "You are now in orbit of the strange magenta type planet."
CIRCLE (639, 479), 400, 5                        'landing #1
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (220, 240), 2      'ship, moon, planet
PSET (221, 240), 2
PSET (222, 240), 2
' Play notes going down the scale
FOR freq = 1600 TO 1400 STEP -30
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange magenta type planet."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (240, 245), 2      'ship, moon, planet
PSET (241, 245), 2
PSET (242, 245), 2
FOR freq = 1400 TO 1200 STEP -30
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange magenta type planet."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (260, 255), 2      'ship, moon, planet
PSET (261, 255), 2
PSET (262, 255), 2
FOR freq = 1200 TO 1000 STEP -30
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange magenta type planet."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (280, 265), 2      'ship, moon, planet
PSET (281, 265), 2
PSET (282, 265), 2
FOR freq = 1000 TO 800 STEP -30
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange magenta type planet."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (300, 275), 2      'ship, moon, planet
PSET (301, 275), 2
PSET (302, 275), 2
FOR freq = 800 TO 600 STEP -30
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange magenta type planet."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (320, 285), 2      'ship, moon, planet
PSET (321, 285), 2
PSET (322, 285), 2
FOR freq = 600 TO 400 STEP -30
        SOUND freq, 1
NEXT freq
CLS
PRINT "You are now in orbit of the strange magenta type planet."
CIRCLE (639, 479), 400, 5
PAINT (638, 478), 5, 5
CIRCLE (139, 139), 32, 8
PAINT (140, 140), 8, 8
PSET (340, 295), 2      'ship, moon, planet
PSET (341, 295), 2
PSET (342, 295), 2
FOR freq = 400 TO 200 STEP -30
        SOUND freq, 1
NEXT freq
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
98 PRINT "You land on the smooth surface of the planet. You see many kinds"
PRINT "of plantlife everywhere. You're not sure why you're here. "
INPUT "Want to leave and come back later? (y/n)"; lea$     'leave NO YES
IF lea$ = "y" THEN GOTO 100:  ELSE GOTO 109
99 CLS
100
PRINT "Now which three planets do you wish to go?" 'SELECTION #2
LINE (100, 80)-(600, 450), 12, B
LINE (101, 81)-(599, 449), 12, B
CIRCLE (179, 129), 6, 15
CIRCLE (179, 129), 5, 11
CIRCLE (179, 129), 4, 9
CIRCLE (179, 129), 3, 1
LOCATE 17, 34
PRINT "-B- Xen Shopping Center"
CIRCLE (319, 239), 6, 4
PAINT (320, 240), 4, 4
LOCATE 7, 16
PRINT "-A- You are here (Numinos)"
CIRCLE (429, 359), 6, 13
PAINT (430, 360), 13, 13
LOCATE 22, 50
PRINT "-C- (Unknown)"
LOCATE 30, 1
101 INPUT "Which letter do you wish to choose (a/b/c)"; akb$
IF akb$ = "a" THEN GOTO 90:   ELSE GOTO 102
102 IF akb$ = "b" THEN GOTO 200:  ELSE GOTO 103
103 IF akb$ = "c" THEN GOTO 300:  ELSE GOTO 101
109 PRINT "You notice an odd path. You look again and see nothing else."
IF sto$ = "b" THEN GOTO 110:  ELSE GOTO 115
110 PRINT "You suddenly feel warm. You can't figure what. Then you fall"
PRINT "to your knees. Then you collapse. You die later of radiation"
PRINT "poisoning." 'PLUTONIUM BAR DEATH
INPUT "Press ENTER"; en$
GOTO 450
115 PRINT "You stroll along, feeling fine. " 'NO PLUTONIUM
PRINT "You come to a big grey building."
CIRCLE (319, 239), 55, 8
PAINT (320, 240), 8, 8
LINE (259, 269)-(499, 319), 8, B
PAINT (260, 270), 8, 8
INPUT "Press ENTER"; en$
200 CLS
PRINT "You zoom into the giant parking lot of the Xen Shopping Center."
PRINT "You can see only 2 stores open now."
PRINT "(a) = Al's Foods"
PRINT "(b) = Joe's survival gear"
PRINT
202 INPUT "Which store do you wish to go in (a/b)"; sto$
IF sto$ = "a" THEN GOTO 240:  ELSE GOTO 204
204 IF sto$ = "b" THEN GOTO 210:  ELSE GOTO 206
206 PRINT "That's not an option. Make sure your answers are in lowercase."
GOTO 202
210 CLS
PRINT "You walk in to see the mutant storekeeper looking at you."
LOCATE 14, 55
PRINT "|Hello, Dirk. Can I "
LOCATE 15, 55
PRINT "|help you?"
CIRCLE (319, 239), 100, 14  'head
PAINT (320, 240), 14, 14
CIRCLE (269, 189), 18, 15  'eye
PAINT (270, 190), 15, 15
CIRCLE (269, 189), 8, 0  'pupil
PAINT (268, 188), 0, 0
CIRCLE (369, 289), 18, 15  'eye
PAINT (370, 290), 15, 15
CIRCLE (369, 289), 8, 0  'pupil
PAINT (368, 288), 0, 0
CIRCLE (319, 269), 20, 0
PAINT (320, 270), 0, 0'mouth
LOCATE 28, 1
PRINT "|Well what do you have?| you asked."
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
PRINT "|Here is our selections|"   'B STORE SELECTIONS
PRINT "(a) = Inflatible tent"
PRINT "(b) = 9ft bar of plutonium"
PRINT "(c) = small little knife"
PRINT "(d) = Inflatible moutain top mansion"
PRINT "(e) = Propane BBQ"
PRINT
212 INPUT "Which item do you wish to have"; hv$
IF hv$ = "a" THEN PRINT "Here ya go. Enjoy.";  ELSE GOTO 213
213 IF hv$ = "b" THEN PRINT "Well enjoy.";  ELSE GOTO 214
214 IF hv$ = "c" THEN PRINT "Well don't cut yer self.";  ELSE GOTO 215
215 IF hv$ = "d" THEN PRINT "I think that costs a little more than you have.";  ELSE GOTO 216
216 IF hv$ = "e" THEN PRINT "Have fun and don't cook any cows!";  ELSE GOTO 218
218 IF hv$ = "" THEN GOTO 212
220 PRINT "You look around and decide to leave."
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
221 PRINT "You walk back to your mobile."
PRINT "Now which two planets do you wish to go?"    'TWO PLANETS
LINE (100, 80)-(600, 450), 12, B
LINE (101, 81)-(599, 449), 12, B
LOCATE 17, 25
PRINT "You are here (XSC)"
CIRCLE (320, 240), 6, 15
CIRCLE (320, 240), 5, 11
CIRCLE (320, 240), 4, 9
CIRCLE (320, 240), 3, 1
LOCATE 17, 34
LOCATE 7, 16
PRINT "-A- Numinos"
LOCATE 17, 22
CIRCLE (179, 129), 6, 5
PAINT (180, 130), 5, 5
CIRCLE (429, 359), 6, 13
PAINT (430, 360), 13, 13
LOCATE 22, 50
PRINT "-B- (Unknown)"
LOCATE 30, 1
222 INPUT "Which letter do you wish to choose (a/b)"; abc$
IF abc$ = "a" THEN GOTO 90:  ELSE GOTO 224
224 IF abc$ = "b" THEN GOTO 300:  ELSE GOTO 232
232 PRINT "That is not an option. All answers must be in lower case."
GOTO 222
240 CLS
PRINT "You walk in and see oodles of food. Then an odd"
PRINT "store worker comes up."
LOCATE 14, 50
CIRCLE (319, 239), 100, 14  'head
PAINT (320, 240), 14, 14
CIRCLE (269, 189), 18, 15  'eye
PAINT (270, 190), 15, 15
CIRCLE (269, 189), 8, 0  'pupil
PAINT (268, 188), 0, 0
CIRCLE (369, 289), 18, 15  'eye
PAINT (370, 290), 15, 15
CIRCLE (369, 289), 8, 0  'pupil
PAINT (368, 288), 0, 0
CIRCLE (319, 269), 20, 0
PAINT (320, 270), 0, 0'mouth

PRINT "|Hello, may I help you?"
LOCATE 30, 1
INPUT "Press ENTER"; en$
CLS
PRINT " |Yes. Do you have a jar of lithium?| you ask."
PRINT
PRINT "| Sorry, but we don't.|"
PRINT "As you leave the store. the other two stores begin to close."
GOTO 221
300 CLS
PRINT "You shoot ofward to the strange unknown planet."
CIRCLE (270, 250), 55, 15 'cockpit
LINE (179, 259)-(360, 320), 2, B 'ship body
PAINT (180, 260), 2, 2
CIRCLE (279, 239), 16, 14 'head
PAINT (280, 240), 14, 14
LINE (155, 250)-(55, 250), 15
LINE (150, 300)-(45, 300), 15
LOCATE 18, 5
PRINT "***ZOOOM!***"
LOCATE 25, 1
INPUT "Press ENTER"; en$
CLS
450 CLS
PRINT "You've died. Oh well. "
PRINT
INPUT "      WOULD YOU LIKE TO PLAY AGAIN (y/n)"; pla$
IF pla$ = "y" THEN GOTO 10:  ELSE GOTO 451
451 IF pla$ = "Y" THEN GOTO 10:  ELSE GOTO 453
453 PRINT "Oh well. "
PRINT
PRINT
PRINT "Try me again soon!"
455 END

