5 CLS
10 BEEP
15 PRINT ""
20 PRINT ""
25 PRINT ""
30 PRINT ""
35 PRINT ""
40 PRINT "                  A           บ บ"
45 PRINT "          HAPPY      TOWNE  บ บ บ บ"
50 PRINT "          PROGRAMMING INC.  บ     บ"
55 PRINT "                            ศอออออผ"
60 PRINT ""
65 PRINT ""
70 PRINT "        PRESENTS..."
75 PRINT ""
80 PRINT ""
85 PRINT ""
90 PRINT ""
95 PRINT ""
100 PRINT ""
105 INPUT "Press ENTER to continue."; e$
110 CLS
115 BEEP
120 PRINT ""
125 PRINT ""
130 PRINT ""
135 PRINT ""
140 PRINT "       อ FANSATSY    ROLE อ"
145 PRINT "                 I       "
150 PRINT "       (THE ULTIMATE FANTASY)"
155 PRINT ""
160 PRINT ""
165 PRINT ""
170 PRINT ""
175 BEEP
180 INPUT "Press ENTER to continue."; e$
196 CLS
197 PRINT "This is no ordinary role play game, but you get to name the other"
198 PRINT "Characters! Is that cool or not?"
199 PRINT ""
200 INPUT "Press ENTER to continue."; e$
201 PRINT ""
202 PRINT "INFO: Please answer every wuestion, by typing in a letter in the ()."
203 PRINT "in all caps. Please. Or you'll get it wrong."
204 PRINT "Also please answer everything in caps all caps except name. just "
205 PRINT "answer like this: Bob. Okay. Good."
210 PRINT ""
215 INPUT "What shall you be called?"; name$
220 PRINT "Welcome, "; name$; "."
225 PRINT ""
230 INPUT "How old do you wish to be?"; age!
235 INPUT "What type of creature do you wish to be?"; cre$
240 PRINT ""
245 PRINT "KNIGHT: FIGHTER: ARCHER: TOWNE DRUNK: PALADIN"
250 INPUT "Please choose one of these selections."; sel$
255 PRINT ""
260 PRINT "Well that's all."
265 PRINT "NAME:    "; name$; ""
270 PRINT "AGE:     "; age!; ""
275 PRINT "CREATURE "; cre$; ""
280 PRINT "TYPE     "; sel$; ""
285 PRINT ""
290 INPUT "Is this correct? (Y/N)."; cor$
295 IF cor$ = "Y" THEN GOTO 310:  ELSE GOTO 300
300 PRINT "Well let's see what's wrong."
305 GOTO 210
310 PRINT "Well I'm glad everything's okay."
315 PRINT "Now let's get with the game."
320 PRINT ""
325 INPUT "Press ENTER to continue."; e$
330 CLS
335 PRINT "You look around the castle and then a knocking comes at your door."

