10 CLS
15 BEEP
30 PRINT ""
40 PRINT ""
45 PRINT "  =====================A======================="
50 PRINT "   HAPPY  TOWNE  PROGRAMMING  INC. PRODUCTION"
55 PRINT "                    "
60 PRINT "                 PRESENTS...."
65 PRINT ""
70 PRINT "   ²²²²²²²      ²²²²²²    ²²²      ²²²²²²²²² "
75 PRINT "   ²²Ûßß²²Û    ²²²Ûß²²²Û  ²²²Û     ²²²Ûßßßßß "
80 PRINT "   ²²Û  ²²Û    ²²²Û ²²²Û  ²²²Û     ²²²Û"
85 PRINT "   ²²²²²²²Û    ²²²Û ²²²Û  ²²²Û     ²²²²²²²²² "
86 PRINT "   ²²²Ûß²²²Û   ²²²Û ²²²Û  ²²²Û     ²²²Ûßßßßß "
87 PRINT "   ²²²Û ß²²²Û  ²²²Û ²²²Û  ²²²Û     ²²²Û"
88 PRINT "   ²²²Û  ²²²Û  ß²²²²²²Ûß  ²²²²²²Û  ²²²²²²²²²² "
89 PRINT "   ßßßß  ßßßß   ßßßßßßß   ßßßßßßß  ßßßßßßßßßß "
90 PRINT "          PLAY O' DEATH  III"
95 PRINT "             (The Journey)"
98 PRINT "         CREATED BY: GARY BURT"
100 PRINT "This is an unregisterd version..."
101 INPUT "Press ENTER to continue."; e$
102 CLS
105 PRINT " ²²²²²²²²²²²²²²²²THEÍSTORY²²²²²²²²²²²²²²²²²²²²²²²²²²²²²"
106 PRINT " ²  You have reined supreme hero of the Uginda World. ²Û"
108 PRINT " ²Now you hear a another cry for help. But not from   ²Û"
110 PRINT " ²your world. It has been sent from a near by world of²Û"
112 PRINT " ²Trensila. You must journey towards the small city of²Û"
114 PRINT " ²Densvilla, where the deranged mage Siko can open a  ²Û"
116 PRINT " ²gate to Trensila. You have arranged a meeting with  ²Û"
118 PRINT " ²Siko. But there is another strange sense that runs  ²Û"
120 PRINT " ²through you, but you just don't know where, what it ²Û"
122 PRINT " ²is. You seem to brush it off you and then you have  ²Û"
124 PRINT " ²everything set up for the 30 mile journey. After a  ²Û"
126 PRINT " ²few miles into your journey, the strange sense comes²Û"
128 PRINT " ²back. You locate the source and find it is a mind   ²Û"
130 PRINT " ²message. Now you have to figure, from who? The short²Û"
132 PRINT " ²message said, 'You must hurry! Do not delay with any²Û"
134 PRINT " ²thing! Do not talk or anything hurry!' Then the     ²Û"
136 PRINT " ²message ends, leaving you with many questions. Now  ²Û"
138 PRINT " ²what? Should you still meet with Siko or not?       ²Û"
140 PRINT " ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²Û"
142 PRINT "  ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß"
144 INPUT "Press ENTER to continue."; e$
146 CLS
148 PRINT " ²²²²²²THE²STORY²CONTINUED...²²²²²²²²²²²²²²²²²²²²²²²²²²²²"
150 PRINT " ²   Now you have some of your questions to fill. First ²Û"
152 PRINT " ²off you must know if it is coming from Trensila or    ²Û"
154 PRINT " ²not? Second, do you still wish to meet with Siko? And ²Û"
156 PRINT " ²third, what is the matter, like, what's is destroying ²Û"
158 PRINT " ²the planet, or what is so bad there? Your brain runs  ²Û"
160 PRINT " ²the questions over and over again, searching for any- ²Û"
162 PRINT " ²thing that can help you answer them. With all your    ²Û"
164 PRINT " ²effort, your questions are not answered. You must find²Û"
166 PRINT " ²the answers, which lie in the near by world of...     ²Û"
168 PRINT " ² TRENSILA!                                            ²Û"
170 PRINT " ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²Û"
172 PRINT "  ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß"
174 PRINT ""
175 INPUT "Press ENTER to continue."; e$
176 CLS
178 PRINT " ²²²²THE²MEETING²WITH²SIKO²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²"
180 PRINT " ²   Your horses come to stop on a large dirt road. There ²Û"
182 PRINT " ²on the side of the road is a middle aged man waving his ²Û"
184 PRINT " ²hand. You and your comrads get off and head towards him.²Û"
186 PRINT " ²Then after a quick 'Hi' You all follow him to his house ²Û"
188 PRINT " ²where you can enter Trensila. You walk up and see a huge²Û"
190 PRINT " ²steal door. The door has to be at least 10 meters tall. ²Û"
192 PRINT " ²Siko leads you to a giant mirror. It was very big. So   ²Û"
194 PRINT " ²big that a Mu Sloth could fit in it!                    ²Û"
196 PRINT " ²   'So, you need me to open the gate?' Siko asks.       ²Û"
198 PRINT " ²   You say yes and his face turns a bit nervous. He bows²Û"
200 PRINT " ²and raises his hands towards the mirror. His hands begin²Û"
202 PRINT " ²to glow. Then a burst of lightning hits the mirror from ²Û"
204 PRINT " ²his hands. Then a big boom is echoed throughout the     ²Û"
206 PRINT " ²building. Then came a hord of goblins! Must have been at²Û"
208 PRINT " ²least 40! They came in rishing towards you and your men.²Û"
210 PRINT " ²One by one your men were slain! And then you and Siko   ²Û"
212 PRINT " ²were the only two left to stop them!                    ²Û"
214 PRINT " ²   'Quickly through!' Siko yelled to you. Then you did! ²Û"
215 PRINT " ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²Û"
216 INPUT "Press ENTER to continue."; e$
218 CLS
219 PRINT "²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²"
220 PRINT "²  And now the adventure begins...                     ²Û"
221 PRINT "²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²Û"
223 PRINT " ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß"
224 INPUT "Press ENTER to continue."; e$
225 CLS
230 INPUT "Please enter your desired name."; name$
232 PRINT "Welcome, "; name$; ""
234 PRINT ""
235 PRINT "Please when answering the questions use only lower case letters."
240 PRINT "Or just type what is the () okay. Thank you..."
245 INPUT "What gender shall you be? (m/f)"; g$
250 PRINT ""
255 PRINT "Human, Orc, Dwarf, Elf, Mutant, Vorun"
260 INPUT "What type of creature do you wish to be?"; cre$
264 PRINT ""
266 PRINT ""
268 INPUT "Please enter a age you wish to be. Please keep it low."; age!
270 PRINT "Thank you, "; name$; ""
272 PRINT ""
274 PRINT "Please choose from the following types of characters."
276 PRINT ""
278 PRINT "FIGHTER  "
280 PRINT ""
282 PRINT "PALADIN  "
284 PRINT ""
286 PRINT "ARCHER  "
288 PRINT ""
290 PRINT "TOWN DRUNK  "
291 PRINT ""
292 PRINT "WIZARD "
294 PRINT "Please type the whole name of the type of character in lower case"
296 PRINT "letters. Thank you."
300 PRINT "Okay which shall it be? A FIGHTER, PALADIN, ARCHER, TOWN DRUNK, or"
305 PRINT "a WIZARD?"
310 INPUT "Please choose one now. In lower case please..."; type$
312 CLS
314 PRINT "How does everything look?"
315 PRINT ""
316 PRINT "Your name is, "; name$; ""
317 PRINT ""
318 PRINT "You are "; g$; ""
319 PRINT "You are a "; cre$; ""
320 PRINT "Your age is "; age!; ""
325 PRINT "You are a "; type$; ""
328 PRINT ""
329 INPUT "Press ENTER to continue."; e$
334 CLS
356 INPUT "Enter a number: ", seed
358 RANDOMIZE (seed)
359 hit% = RND * 40 + 1
360 PRINT hit%
366 INPUT "Press ENTER to continue."; e$
368 CLS
370 PRINT "Okay here's what you have..."
372 PRINT "Your name is "; name$; ""
374 PRINT "Your age is "; age!; ""
375 PRINT "You are a "; cre$; ""
378 PRINT "Your type of character is "; type$; ""
380 PRINT "Your gender is "; g$; ""
382 PRINT "Your hit points ="; hit%
390 PRINT ""
392 PRINT "All right! Everything looks good! Let's get going to the game!"
394 PRINT "Okay! Ready set go!"
396 INPUT "Press ENTER to continue."; e$
398 CLS
400 BEEP
402 PRINT ""
404 PRINT ""
405 PRINT ""
410 PRINT "You rush through the portal and wind up in the most bizzare   "
412 PRINT "world. You look back to see some of the goblins had made it "
414 PRINT "through! You begin to run, but soon relize it is useless!"
416 PRINT "You have no choice, but to fight! And hurry, cause they're"
418 PRINT "catching up!"
420 INPUT "Are you going to 1=attack straight forward, or 2=run around the side?"; st!
422 IF st! = 2 THEN GOTO 445:  ELSE GOTO 424
424 CLS
425 PRINT "You run straight forward towards them and then they dodge your"
426 PRINT "pitiful attack! Then they pin you and then take swipes at you!"
427 PRINT "You are slashed over and over till you finally are dead. Then the"
430 PRINT "goblins leave. "
435 PRINT "You are dead... Hey it ain't my fault! It's yours!"
440 PRINT "Bye, "; name$; ". It was nice knowing you. Ha ha ha!"
441 INPUT "Press ENTER to continue."; e$
442 GOTO 1020
445 CLS
446 BEEP
448 PRINT "You run at them and then tunr to their side. They never expected"
450 PRINT "that type of move! You pull out your sword and then swing each one"
452 PRINT "down then "
455 INPUT "Enter a number: ", seed
458 RANDOMIZE (seed)
460 ex% = RND * 20 + 1
466 PRINT ex%
468 PRINT "You have earned"; ex%; " experience points!!"
470 PRINT "You look at the bodies and continue to explorer."
472 INPUT "Press ENTER to continue."; e$
474 CLS
476 PRINT "You walk onward and meet up to a sign it shows three places."
478 PRINT "One of which is a town, another a village, and the third a "
480 PRINT "castle."
482 PRINT ""
484 INPUT "Are you going to the town? (y/n)"; to$
485 IF to$ = "y" THEN GOTO 530:   ELSE GOTO 486
486 INPUT "How about the village? (y/n)"; vil$
487 IF vil$ = "y" THEN GOTO 494:  ELSE GOTO 488
488 INPUT "OKay last one, how about the castle? (y/n)"; cas$
490 IF cas$ = "y" THEN GOTO 505:  ELSE GOTO 491
491 PRINT ""
492 PRINT "Hey you have to go somewhere! What an ego!"
493 GOTO 482
494 CLS
495 PRINT "You shrug and walk onward to the village. In about an hour, you"
496 PRINT "get to a gate and begin to knock on it. A strange litlle creature"
497 PRINT "stares at you. It begins to make a weird bird sound, then the gate"
498 PRINT "opens. You cautiously walk in, to see a hord of villagers with "
499 PRINT "spears. They run up and kill you instantly!"
500 PRINT "Way to go, "; name$; ". You're dead! Not my fault!"
502 PRINT "Bye, "; name$; ""
503 INPUT "Press ENTER to continue."; e$
504 GOTO 1020
505 CLS
506 PRINT "You feel the castle, seems fine, then as you get walking along"
508 PRINT "you get a sudden chill. As if somebody was watching you."
510 PRINT "You turn at every sound. You begin to get paranoid. You fall"
515 PRINT "to the ground and pass out. Later on you die."
520 PRINT "You are now dead, "; name$; ". Hey! It ain't my fault!"
523 INPUT "Press ENTER to continue."; e$
528 GOTO 1020
530 CLS
532 PRINT "You decide to head to the the town. Of course it didn't take you"
534 PRINT "long to get there. You walk in through the gates. You notice, your"
535 PRINT "clothing doesn't fit in. You foget about that, and talk to some-"
540 PRINT "body. "
542 PRINT "   'Hello, I'm, "; name$; ". Can you tell me where I am?' you ask."
544 PRINT "The man tells you the name of the town, which is, 'Sacrin' and"
545 PRINT "tells you, you are on TRENSILA. YOu thank him and scurry off."
546 PRINT ""
548 BEEP
550 INPUT "Press ENTER to continue."; e$
552 CLS
555 PRINT "You walk along a nice market street, when you are pulled in an"
558 PRINT "alley. You see four men in dark clothing looking at you."
560 PRINT "   'Please come with us, "; name$; ".' on says."
562 PRINT ""
564 INPUT "Are you going to trust him? (y/n)"; him$
565 IF him$ = "y" THEN GOTO 580:  ELSE GOTO 566
566 CLS
568 PRINT "You start to back away shaking your head. They beg you and then"
570 PRINT "runaway horse slams into your side and then crushes you to death."
575 PRINT "Yo, "; name$; "! You're dead! And it's not my fault!"
576 PRINT "Ha ha ha! Moron! Ha ha ha!"
577 INPUT "Press ENTER to continue."; e$
580 CLS
582 BEEP
584 PRINT "You agree to follow, them and then they take you down into the"
585 PRINT "sewers. Yo have a strange uneasiness flow through you. But you"
586 PRINT "keep following them. Then you enter a large mildly bright room."
588 PRINT "You see a strange creature. It's body is human, but its face is"
590 PRINT "shaped of a rats, and has donkey ears. It rises from its chair and"
592 PRINT "The strange men take off their masks, to have the same face as their"
594 PRINT "leader. You say hello and it begins to speak."
596 PRINT "   'I am Cronos. I am the leader of the Skikae. I have summond"
598 PRINT "you, "; name$; " to help my people. I cannot give you the full"
600 PRINT "details, because we don't have much time. You must get the eye"
602 PRINT "of Ali Muadeeb. There we can place it in our temple, thus for,"
604 PRINT "putting the Dynasyyyk asleep, for another 8 billion years.'"
606 PRINT "Cronos gives you all the details and has you dropped off near the"
608 PRINT "place where the eye is. You take a quick sigh and move in..."
610 PRINT ""
615 INPUT "Press ENTER to conrinue."; e$
618 CLS
620 PRINT "You notice two guards are posted out by the gate. You can A=go and"
625 PRINT "straight forward kill them, or B= you can devert their attentions"
630 PRINT "to something else."
632 INPUT "Which is it going to be? (a/b)"; ab$
634 IF ab$ = "a" THEN GOTO 635:  ELSE GOTO 665
635 CLS
636 PRINT "You go ahead and charge directly towards them. They quickly move"
638 PRINT "out of your way and then swipe at you!"
640 INPUT "Enter a number: ", seed
645 RANDOMIZE (seed)
648 de% = RND * 40 + 1
650 IF de% >= hit% THEN GOTO 655:   ELSE GOTO 658
655 PRINT de%
656 PRINT "You are now nearly dead! They take one more wack and you die!"
657 PRINT "Nice going, "; name$; ". You idiot. You destroyed a world! Gees!"
658 PRINT "Well bye!!"
659 INPUT "Press ENTER to continue."; e$
660 GOTO 1020
661 PRINT "You took more than one hit, "; name$; ". That's cool! Hu hu hu hu!"
662 PRINT "Well, "; name$; ". You died! Way to go!"
663 PRINT "BYE!"
664 GOTO 1020
665 CLS
668 PRINT "You grab the nearest rock and throw it towards another bush about"
670 PRINT "a few meters away. They look in that direction, and you shoot out"
675 PRINT "a spear hitting one of the guards. Then another sees you and sets "
678 PRINT "off the alarm! Then you throw the other spear hitting him too."
680 PRINT ""
682 INPUT "Enter any number: ", seed
684 RANDOMIZE (seed)
686 exs% = RND * 20 + ex%
687 PRINT exs%
688 PRINT "Your total experience points are "; exs%; ""
690 BEEP
691 BEEP
692 BEEP
693 BEEP
695 INPUT "Press ENTER to continue."; e$
700 CLS
705 PRINT "You see hords of strange looking guards charging out of the building"
710 PRINT "to see there dead comrads. All right you have your chance to go in."
713 PRINT "You can A=Sneak around towards the side and slip in, B= You can try"
714 PRINT "to negotiate with them in letting you in, or C= Disguise yourself as"
718 PRINT "one of the guards."
720 INPUT "Which shall it be? (a/b/c)."; dis$
725 IF dis$ = "c" THEN GOTO 760:  ELSE GOTO 730
730 IF dis$ = "b" THEN GOTO 732:  ELSE GOTO 754
732 CLS
733 PRINT "You walk very casual up to the guards and intorduce yourself. You"
734 PRINT "tell them of the Dynasyyyk and they laugh histaracolly! Then they"
735 PRINT "decide to put the blame on you for killing their friends and they"
736 PRINT "stab you once."
737 INPUT "Enter a number: ", seed
738 RANDOMIZE (seed)
739 des% = RND * 40 + 1
740 PRINT "You lost, "; des%; " hit points."
741 IF des% >= hit% THEN GOTO 745:  ELSE GOTO 748
745 PRINT "You die on the first blow. Nice going, "; name$; "!"
746 INPUT "Press ENTER to continue."; e$
647 GOTO 1020
748 PRINT "You still live, so they stab you again. You bleed to death."
749 PRINT " Smooth Move, "; name$; ". You just died! And it ain't my fault!"
751 INPUT "Press ENTER to continue."; e$
752 GOTO 1020
753 CLS
754 PRINT "You sneak around to the side and slowly move in. One guard sees"
755 PRINT "you and tells teh others. You are still unaware. Then they capture"
756 PRINT "you and your hauled off to the town jail, where you rot till the"
757 PRINT "Dynasyyyk comes and destroys the world! Nice going, "; name$; ""
758 PRINT "I could have done better in my sleep."
759 INPUT "Press ENTER to continue."; e$
760 GOTO 1020
761 CLS
762 PRINT "You grab one of the unexpecting guards and take his uniform. Then "
764 PRINT "hop out of the bushes and walk back into the building. You walk in"
765 PRINT "and see the eye in a steal cage. You think for a moment and wonder"
770 PRINT "if you should take the cage. Then a guard comes up to you."
775 PRINT "   'All right! What are you doing here?!' The guard asks you."
780 PRINT ""
785 PRINT "You could tell him, 'That you were orderes to.' = A"
786 PRINT "or tell him that 'You cannot say, on high authority.' =B"
788 INPUT "Which one shall you say? (a/b)."; des$
790 IF des$ = "a" THEN GOTO 820:  ELSE GOTO 792
792 CLS
794 PRINT "   'I cannot say, on high authority.' you say. "
796 PRINT "The guard gave you a odd look and then, after many minutes of"
798 PRINT "converstation, with the guard, you get arrested. The guard did"
800 PRINT "believe a word you said. You get thrown in jail and rot till the"
805 PRINT "Dynasyyyk comes, which was very soon. And you and Trensila die."
810 PRINT "Congradulations, "; name$; ". you died! Not my fault! Ha ha ha!"
812 INPUT "Press ENTER to continue."; e$
815 GOTO 1020
820 CLS
822 PRINT "   'I was ordered to this area.'  you say to the guard."
825 PRINT "The guard shrugs and leaves, then you are alone. You have your"
828 PRINT "chance to take the eye. Are you going to take it?"
830 INPUT "Well are you going to take it? (y/n)."; take$
832 IF take$ = "y" THEN GOTO 850:  ELSE GOTO 834
834 CLS
836 PRINT "You decide not to take it, and then a quake shakes you. The whole"
840 PRINT "building even the city shake, and the eye falls and breaks into many"
842 PRINT "pieces. You have lost the chance to save this world. the quakes continue"
845 PRINT "till everything is covered with lava! You die! Nice going, "; name$; ""
846 PRINT "You idiot."
848 INPUT "Press ENTER to continue."; e$
849 GOTO 1020
850 CLS
851 PRINT "You double check to see if you are alone, and then grab the cage."
854 PRINT "As you hold it tight a quake starts. Oh no! It has to be the "
855 PRINT "Dynasyyyk awakening! You quickly leave the building during the"
858 PRINT "comotion, from the shake. You run out to see Cronos waiting. He "
860 PRINT "some of his people lead you to the temple. You see there are four"
865 PRINT "eye sockets on the statue. They did not know which one it goes"
870 PRINT "into. Now you're in trouble. "
875 PRINT "You have four choices 1,2,3. or 4. You have to choose quickly."
880 INPUT "Which number are you going to choose? (1/2/3/4)."; cho!
884 IF cho! = 3 THEN GOTO 900:  ELSE GOTO 885
885 CLS
886 PRINT "You choose one eye socket and carefully put it in. The shaking"
888 PRINT "stops. You blow a sigh, then a crack opens, lava oozes out and"
890 PRINT "The shaking starts up again. The eye falls out and knocks you out"
892 PRINT "into the lava. You just died, "; name$; ""
895 INPUT "Press ENTER to continue."; e$
898 GOTO 1020
900 CLS
905 PRINT "You choose a quick socket and then the shaking stops. You blow a"
910 PRINT "sigh of relief and then the statue's arms move."
915 PRINT "They spread out forming two portals, one red and the other blue."
920 PRINT "   'You may choose your path. One will lead you home, the other to"
925 PRINT "death! You must first proove your self worthy, by answering one"
930 PRINT "question. There is only one aswer I will except. Think carefully."
935 INPUT "What in all the universe should you want?"; want$
940 IF want$ = "peace" THEN GOTO 960:  ELSE GOTO 942
942 CLS
945 PRINT " you guess, "; want$; ". The statue is not pleased and you are"
948 PRINT "forced into the red portal! You feel extreme heat. Then you burn"
950 PRINT "into a giant fire ball, and fly through the void, forever, feeling"
952 PRINT "pain till the end of eternity."
955 PRINT "You have lost, "; name$; ". It was nice knowing you."
956 INPUT "Press ENTER to continue."; e$
958 GOTO 1020
960 CLS
962 PRINT "You guess, "; want$; ", and the statue is pleased. The red portal"
965 PRINT "dissapears, and you walk into the blue one. You find yourself in"
968 PRINT "Siko's house, he and your companions alive, and no sign of goblins."
970 PRINT "You tell your companions about your adventure, and they give you a"
975 PRINT "odd look. Then they laugh and you head back home..."
980 INPUT "Press ENTER to continue."; e$
985 CLS
990 BEEP
991 BEEP
992 BEEP
993 BEEP
994 BEEP
995 BEEP
996 PRINT "Congradulaionts, "; name$; "You beat Role3! You have one it with"
998 PRINT "a total amount of, "; exs%; " experience points! Nice going!!!"
1000 PRINT "Wow! Good work, "; name$; "! You did good!!"
1005 INPUT "On a scale of 1-10 what would you give this game?"; game!
1010 IF game! >= 5 THEN GOTO 1018:  ELSE GOTO 1011
1011 PRINT "Oh, okay. Well this is an unregistered version!"
1012 PRINT ">sigh<"
1013 GOTO 920
1018 PRINT "Oh goody! I think you deserve a, "; game!; " or better!"
1019 PRINT "Thank you, "; name$; "! I like you!"
1020 BEEP
1022 PRINT "Good job once again! You are king of the mountain!!!"
1025 INPUT "Press ENTER to continue."; e$
1030 CLS
1032 PRINT "Here are your stats."
1033 PRINT ""
1035 PRINT "Your name is, "; name$; ""
1036 PRINT "You are, "; g$; ""
1037 PRINT "You are a, "; cre$; ""
1038 PRINT "You age is, "; age!; ""
1040 PRINT "You are a proud, "; type$; ""
1046 PRINT "You have, "; hit%; " hit points."
1055 PRINT "Good work, "; name$; "."
1060 BEEP
1065 INPUT "Press ENTER to continue."; e$
1066 CLS
1070 BEEP
1075 PRINT ""
1080 PRINT ""
1085 PRINT ""
1090 PRINT "You win the game with, "; exs%; " experience points!!"
1095 PRINT "Nice killing, "; name$; ". You got alot of experience points!"
1100 PRINT ""
1101 PRINT ""
1108 PRINT ""
1110 INPUT "Press ENTER to continue."; e$
1120 CLS
1130 BEEP
1140 BEEP
1150 PRINT "Remember, this is not a registered version! Please register!!"
1160 PRINT "INFO on how to register next page. "
1170 PRINT ""
1180 PRINT ""
1200 INPUT "Press ENTER to continue."; e$
1220 CLS
1230 PRINT ""
1240 PRINT ""
1250 PRINT ""
1260 INPUT "Would you like to quit? (y/n)."; qui$
1270 IF qui$ = "y" THEN GOTO 1280:  ELSE GOTO 225
1280 PRINT "Thank you, "; name$; ""
1290 INPUT "Press ENTER to continue."; e$
1300 CLS
1310 BEEP
1320 PRINT ""
1330 PRINT "To register, send $2.00 TO:   Happy Towne Programming Inc."
1340 PRINT "                              2395 East Bernadine Dr."
1350 PRINT "                              Salt Lake City, Utah"
1360 PRINT "                                    84109"
1370 PRINT "                                  "
1380 PRINT "Thank you, "; name$; "."
1390 PRINT ""
1400 INPUT "Press ENTER to continue."; e$
1410 CLS
1420 PRINT ""
1430 PRINT ""
1440 PRINT ""
1450 PRINT ""
1460 PRINT ""
1470 PRINT ""
1480 INPUT "On a scale of 1-10 what would you give this game? (1-10)."; sca!
1490 IF sca! >= 5 THEN PRINT "Oh i am so happy!!";  ELSE PRINT "Oh I see.. (sob)."
1500 PRINT ""
1510 PRINT "Thank's for playing and try me again soon, "; name$; ""
1520 PRINT ""
1530 PRINT ""
1540 PRINT "         ²   ² "
1550 PRINT "         ²Û  ²Û"
1560 PRINT "      ²  ²Û  ²Û  ²"
1570 PRINT "      ²Û ßß  ßß  ²Û"
1575 PRINT "      ²Û         ²Û"
1580 PRINT "       ²²²²²²²²²²Ûß"
1585 PRINT "       ßßßßßßßßßßß"
1590 PRINT ""
1600 BEEP
1601 PRINT "     !!BYE!!"
1610 END

