10 CLS
COLOR 4, 0
LOCATE 8, 1
PRINT "E"
LOCATE 8, 78
PRINT "P"
PLAY "L15 D"
LOCATE 8, 1
PRINT "SE"
LOCATE 8, 77
PRINT "PI"
PLAY "E"
LOCATE 8, 1
PRINT "PSE"
LOCATE 8, 76
PRINT "PIC"
PLAY "F"
LOCATE 8, 1
PRINT "YPSE"
LOCATE 8, 75
PRINT "PICT"
PLAY "G#"
LOCATE 8, 1
PRINT "LYPSE"
LOCATE 8, 74
PRINT "PICTU"
PLAY "A"
LOCATE 8, 1
PRINT "ALYPSE"
LOCATE 8, 73
PRINT "PICTUR  "
PLAY "G#"
LOCATE 8, 1
PRINT "CALYPSE"
LOCATE 8, 72
PRINT "PICTURE "
PLAY "F"
LOCATE 8, 1
PRINT "OCALYPSE"
LOCATE 8, 71
PRINT "PICTURES "
PLAY "E"
LOCATE 8, 1
PRINT "POCALYPSE"
LOCATE 8, 70
PRINT "PICTURES  "
PLAY "D"
LOCATE 8, 1
PRINT "APOCALYPSE"
LOCATE 8, 70
PRINT "PICTURES  "
PLAY "E"
LOCATE 8, 1
PRINT " APOCALYPSE"
LOCATE 8, 69
PRINT "PICTURES  "
PLAY "F"
LOCATE 8, 1
PRINT "  APOCALYPSE"
LOCATE 8, 68
PRINT "PICTURES  "
PLAY " G#"
LOCATE 8, 2
PRINT "  APOCALYPSE"
LOCATE 8, 67
PRINT "PICTURES  "
PLAY "A"
LOCATE 8, 3
PRINT "  APOCALYPSE"
LOCATE 8, 66
PRINT "PICTURES  "
PLAY "G#"
LOCATE 8, 4
PRINT "  APOCALYPSE"
LOCATE 8, 65
PRINT "PICTURES  "
PLAY "F"
LOCATE 8, 5
PRINT "  APOCALYPSE"
LOCATE 8, 64
PRINT "PICTURES  "
PLAY "L17 E"
LOCATE 8, 6
PRINT "  APOCALYPSE"
LOCATE 8, 63
PRINT "PICTURES  "
PLAY "D"
LOCATE 8, 7
PRINT "  APOCALYPSE"
LOCATE 8, 62
PRINT "PICTURES  "
PLAY "E"
LOCATE 8, 8
PRINT "  APOCALYPSE"
LOCATE 8, 61
PRINT "PICTURES  "
PLAY "F"
LOCATE 8, 9
PRINT "  APOCALYPSE"
LOCATE 8, 60
PRINT "PICTURES  "
PLAY "L18 G#"
LOCATE 8, 10
PRINT "  APOCALYPSE"
LOCATE 8, 59
PRINT "PICTURES  "
PLAY "A"
LOCATE 8, 11
PRINT "  APOCALYPSE"
LOCATE 8, 58
PRINT "PICTURES  "
PLAY "G#"
LOCATE 8, 12
PRINT "  APOCALYPSE"
LOCATE 8, 57
PRINT "PICTURES  "
PLAY "F"
LOCATE 8, 13
PRINT "  APOCALYPSE"
LOCATE 8, 56
PRINT "PICTURES  "
PLAY "L19 E"
LOCATE 8, 14
PRINT "  APOCALYPSE"
LOCATE 8, 55
PRINT "PICTURES  "
PLAY "L19 D"
LOCATE 8, 15
PRINT "  APOCALYPSE"
LOCATE 8, 54
PRINT "PICTURES  "
PLAY "L20 E"
LOCATE 8, 16
PRINT "  APOCALYPSE"
LOCATE 8, 53
PRINT "PICTURES  "
PLAY "L20 F"
LOCATE 8, 17
PRINT "  APOCALYPSE"
LOCATE 8, 52
PRINT "PICTURES  "
PLAY "L20 G#"
LOCATE 8, 18
PRINT "  APOCALYPSE"
LOCATE 8, 51
PRINT "PICTURES  "
PLAY "A"
LOCATE 8, 19
PRINT "  APOCALYPSE"
LOCATE 8, 50
PRINT "PICTURES  "
PLAY "G#"
LOCATE 8, 20
PRINT "  APOCALYPSE"
LOCATE 8, 49
PRINT "PICTURES  "
PLAY "L20 F"
LOCATE 8, 21
PRINT "  APOCALYPSE"
LOCATE 8, 48
PRINT "PICTURES  "
PLAY "L21 E"
LOCATE 8, 22
PRINT "  APOCALYPSE"
LOCATE 8, 47
PRINT "PICTURES  "
PLAY "L22 D"
LOCATE 8, 23
PRINT "  APOCALYPSE"
LOCATE 8, 46
PRINT "PICTURES  "
PLAY "E"
LOCATE 8, 24
PRINT "  APOCALYPSE"
LOCATE 8, 45
PRINT "PICTURES  "
PLAY "F"
LOCATE 8, 25
PRINT "  APOCALYPSE"
LOCATE 8, 44
PRINT "PICTURES  "
PLAY "G#"
LOCATE 8, 25
PRINT "  APOCALYPSE"
LOCATE 8, 43
PRINT "PICTURES  "
PLAY "A "
LOCATE 8, 25
PRINT "  APOCALYPSE"
LOCATE 8, 42
PRINT "PICTURES  "
PLAY "L22 G#"
LOCATE 8, 25
PRINT "  APOCALYPSE"
LOCATE 8, 41
PRINT "PICTURES  "
PLAY "L22 F "
LOCATE 8, 25
PRINT "  APOCALYPSE"
LOCATE 8, 40
PRINT "PICTURES  "
PLAY "L22 E "
LOCATE 8, 25
PRINT "  APOCALYPSE"
LOCATE 8, 39
PRINT "PICTURES  "
BEEP
LOCATE 9, 32
COLOR 8, 0
PRINT "presents..."
PLAY "L6 A."
BEEP
BEEP
BEEP
CLS
COLOR 2, 0
PRINT
PLAY "L18 < B. > C D."
PRINT " ²²²²²²²²Ü      ²²²²²²Ü       ²²²²Ü         ²²²²²²²²²²²²Ü"
PLAY "C# < B > "
PRINT " ²²²Ûßß²²Û     ²²²Ûß²²Û       ²²²²Û         ²²²²Ûßßßßßßßß"
PLAY "C# E"
PRINT " ²²²²²²²Û      ²²²Û ²²Û       ²²²²Û         ²²²²²²²²²²²²Ü"
PLAY "< A L6 F"
PRINT " ²²Ûßß²²²Ü     ²²²Û ²²Û       ²²²²Û         ²²²²Ûßßßßßßßß"
PLAY "L16 E C#"
PRINT " ²²Û  ß²²²Ü     ²²²²²Û        ²²²²²²²²²²Ü   ²²²²²²²²²²²²Ü"
PLAY "L6 A >"
PRINT " ßßß    ßßß      ßßßßß         ßßßßßßßßßß    ßßßßßßßßßßßß   "
BEEP
COLOR 10, 0
LOCATE 9, 20
PRINT " PLAY O' DEATH I"
BEEP
COLOR 15, 0
LOCATE 19, 1
PRINT "Copywrite 1996 Apocalypse Pictures. All Rights Reserved. Apocalypse "
PRINT "Pictures is a registered trademark of Apocalypse Productions Inc. Role"
PRINT "Play O' Death is a trademark of Apocalypse Pictures Inc. Apocalypse "
PRINT "Productions Inc. is a registered trademark of Apocalypse Pictures."
PRINT "All rights reserved. Apocalypse Pictures copywrite 1995."
COLOR 4, 0
LOCATE 15, 24
INPUT "Press ENTER to continue.", en$
15 CLS
COLOR 12, 0
PRINT "  °°°°°°°°°°°°°°°±±±±±±±±±±±±±±±±±²²²²²²²²²²²²²²²²²²ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ"
PRINT "         ROLE PLAY O' DEATH  MAIN MENU"
PRINT "  °°°°°°°°°°°°°°°±±±±±±±±±±±±±±±±±²²²²²²²²²²²²²²²²²²ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ"
PRINT
COLOR 4, 0
PRINT " (1)  INTRODUCTION"
PRINT
PRINT " (2)  PLAY THE GAME"
PRINT
PRINT " (3)  CREDITS & STUFF"
PRINT
PRINT " (4)  QUIT THE GAME"
PRINT
COLOR 9, 0
20 INPUT "Select an option. ", op!
IF op! = 1 THEN GOTO 100:  ELSE GOTO 21
21 IF op! = 2 THEN GOTO 200:  ELSE GOTO 22
22 IF op! = 3 THEN GOTO 50:  ELSE GOTO 23
23 IF op! = 4 THEN GOTO 30:  ELSE GOTO 24
24 IF op! > 4 THEN GOTO 28:  ELSE GOTO 15
28 BEEP
GOTO 15
30 END                                          'THE ENDING OF OUR STORY
50 BEEP
CLS
COLOR 15, 0
PRINT "        ====CREDITS======"
COLOR 4, 0
PRINT "Role Play O' Death designed by Apocalypse Pictures Inc."
COLOR 14, 0
PRINT
PRINT "Produced by Apocalypse Productions Inc."
PRINT
COLOR 2, 0
PRINT "Music by 'Me'"
COLOR 1, 0
PRINT
PRINT "Graphics design by 'Me'"
PRINT
COLOR 5, 0
PRINT "Everything by 'Me'"
PRINT
COLOR 6, 0
PRINT
PRINT "Thanks for playing Role Play O' Death!"
PRINT "Sequel due out by end of 1996"
PLAY "L16 < B. > C D. C# D. C# D. C# L4 D L16 E. <B > L4 C L16 D. < A L4 B"
PLAY "L16 G. A B. A# B. A# B. A# L4 B L16 A. G G. F# F#. A G. E L4 D >"
BEEP
GOTO 15
100  CLS
BEEP
COLOR 4, 0
PRINT "Deep in the heart of space a small planet's exsistance hangs in the balance."
PRINT "The planet had no idea of the fate that was about to fall upon it, nor"
PRINT "did it have the knowledge of the greatest battle that was to befall it."
PRINT "Only a small kingdom on the planet was aware and amassed an army to fight"
PRINT "the scheduled pestilence. "
COLOR 15, 0
INPUT "", en$
PRINT
PRINT
PRINT
COLOR 12, 0
PRINT "You have been summoned to the King. Your quest begins..."
INPUT "", en$
CLS
COLOR 6, 8


200

